/*
 * PROJECT:   Mouri Internal Library Essentials
 * FILE:      Mile.HyperV.TLFS.Staged.h
 * PURPOSE:   Definition for Hyper-V Top Level Functional Specification 6.0b
 *
 * LICENSE:   The MIT License
 *
 * MAINTAINER: MouriNaruto (Kenji.Mouri@outlook.com)
 */

#ifndef MILE_HYPERV_TLFS_STAGED
#define MILE_HYPERV_TLFS_STAGED

/* Staged (unused) definitions of Mile.HyperV.TLFS */

#include "Mile.HyperV.TLFS.h"

/*
 * Hypercall Code
 */

/* Defined Hypercall ID in TLFS, but have no detailed definitions */

#define HVCALL_CREATE_PARTITION 0x0040
#define HVCALL_GET_PARTITION_ID 0x0046
#define HVCALL_POST_DEBUG_DATA 0x0069
#define HVCALL_RETRIEVE_DEBUG_DATA 0x006A
#define HVCALL_RESET_DEBUG_SESSION 0x006B
#define HVCALL_GET_SYSTEM_PROPERTY 0x007B

/* Defined Hypercall ID in TLFS, but Parent / Root Partition only */

#define HVCALL_INITIALIZE_PARTITION 0x0041
#define HVCALL_FINALIZE_PARTITION 0x0042
#define HVCALL_DELETE_PARTITION 0x0043
#define HVCALL_GET_PARTITION_PROPERTY 0x0044
#define HVCALL_SET_PARTITION_PROPERTY 0x0045
#define HVCALL_DEPOSIT_MEMORY 0x0048
#define HVCALL_WITHDRAW_MEMORY 0x0049
#define HVCALL_MAP_GPA_PAGES 0x004B
#define HVCALL_UNMAP_GPA_PAGES 0x004C
#define HVCALL_INSTALL_INTERCEPT 0x004D
#define HVCALL_CREATE_VP 0x004E
#define HVCALL_CLEAR_VIRTUAL_INTERRUPT 0x0056
#define HVCALL_DELETE_PORT 0x0058
#define HVCALL_DISCONNECT_PORT 0x005B
#define HVCALL_ADD_LOGICAL_PROCESSOR 0x0076
#define HVCALL_MAP_DEVICE_INTERRUPT 0x007C
#define HVCALL_UNMAP_DEVICE_INTERRUPT 0x007D
#define HVCALL_NOTIFY_PORT_RING_EMPTY 0x008B
#define HVCALL_REGISTER_INTERCEPT_RESULT 0x0091
#define HVCALL_CREATE_PORT 0x0095
#define HVCALL_CONNECT_PORT 0x0096

/* Not even defined Hypercall ID in TLFS */

#define HVCALL_SIGNAL_EVENT_DIRECT 0x00C0
#define HVCALL_POST_MESSAGE_DIRECT 0x00C1
#define HVCALL_DISPATCH_VP 0x00C2
#define HVCALL_GET_GPA_PAGES_ACCESS_STATES 0x00C9
#define HVCALL_MAP_VP_STATE_PAGE 0x00E1
#define HVCALL_UNMAP_VP_STATE_PAGE 0x00E2
#define HVCALL_GET_VP_STATE 0x00E3
#define HVCALL_SET_VP_STATE 0x00E4
#define HVCALL_GET_VP_CPUID_VALUES 0x00F4

#endif /* !MILE_HYPERV_TLFS_STAGED */
