/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'hyperkbd.sys'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _GUID;
struct _DEVICE_OBJECT;
struct _DRIVER_OBJECT;
struct _DRIVER_EXTENSION;
struct _VPB;
struct _SECTION_OBJECT_POINTERS;
struct _FILE_OBJECT;
struct _IO_COMPLETION_CONTEXT;
struct _FILE_BASIC_INFORMATION;
struct _FILE_STANDARD_INFORMATION;
struct _FILE_NETWORK_OPEN_INFORMATION;
struct _OWNER_ENTRY;
struct _ERESOURCE;
struct _MDL;
struct _COMPRESSED_DATA_INFO;
struct _IRP;
struct _SECURITY_QUALITY_OF_SERVICE;
struct _ACCESS_STATE;
struct _IO_SECURITY_CONTEXT;
struct _NAMED_PIPE_CREATE_PARAMETERS;
struct _MAILSLOT_CREATE_PARAMETERS;
struct _FILE_GET_QUOTA_INFORMATION;
struct _INTERFACE;
struct _DEVICE_CAPABILITIES;
struct _IO_RESOURCE_REQUIREMENTS_LIST;
struct _POWER_SEQUENCE;
struct _CM_RESOURCE_LIST;
struct _IO_STACK_LOCATION;
struct _FAST_IO_DISPATCH;
struct _KDPC;
struct _DEVOBJ_EXTENSION;
struct WDFQUEUE__;
struct WDFDEVICE__;
struct VMBCHANNEL__;
struct _DV_RUNDOWN_BARRIER_WAIT_BLOCK;

/* 584 */
struct $9173FCD3816CC8B2C9B7B935B941AC3F
{
  __int32 RightShift : 1;
  __int32 RightCtrl : 1;
  __int32 RightAlt : 1;
  __int32 Reserved : 1;
  __int32 LeftShift : 1;
  __int32 LeftCtrl : 1;
  __int32 LeftAlt : 1;
  __int32 FirstTime : 1;
  __int32 SecondTime : 1;
};

/* 585 */
union _HK_CRASH_DUMP_FLAGS
{
  $9173FCD3816CC8B2C9B7B935B941AC3F Flags;
  int Value;
};

/* 582 */
struct _KEYBOARD_ID
{
  unsigned __int8 Type;
  unsigned __int8 Subtype;
};

/* 571 */
struct _KEYBOARD_TYPEMATIC_PARAMETERS
{
  unsigned __int16 UnitId;
  unsigned __int16 Rate;
  unsigned __int16 Delay;
};

/* 583 */
struct _KEYBOARD_ATTRIBUTES
{
  _KEYBOARD_ID KeyboardIdentifier;
  unsigned __int16 KeyboardMode;
  unsigned __int16 NumberOfFunctionKeys;
  unsigned __int16 NumberOfIndicators;
  unsigned __int16 NumberOfKeysTotal;
  unsigned int InputDataQueueLength;
  _KEYBOARD_TYPEMATIC_PARAMETERS KeyRepeatMinimum;
  _KEYBOARD_TYPEMATIC_PARAMETERS KeyRepeatMaximum;
};

/* 556 */
struct _KEYBOARD_INDICATOR_PARAMETERS
{
  unsigned __int16 UnitId;
  unsigned __int16 LedFlags;
};

/* 581 */
struct _DV_RUNDOWN_BARRIER
{
  int Counter;
  _DV_RUNDOWN_BARRIER_WAIT_BLOCK *WaitBlock;
};

/* 133 */
struct $08481D05807C14C022C64127DBCB0DC5
{
  unsigned __int8 Type;
  unsigned __int8 Signalling;
  unsigned __int8 Size;
  unsigned __int8 Reserved1;
};

/* 134 */
struct $BDD1DEEA9085FB2031C94E38C028AF9F
{
  unsigned __int8 TimerType;
  unsigned __int8 TimerControlFlags;
  unsigned __int8 Hand;
  unsigned __int8 TimerMiscFlags;
};

/* 135 */
struct $1A64267CB6701B751C40AA7938D55A2C
{
  unsigned __int8 Timer2Type;
  unsigned __int8 Absolute : 1;
  unsigned __int8 Wake : 1;
  unsigned __int8 EncodedTolerableDelay : 6;
  unsigned __int8 Timer2Reserved1;
  unsigned __int8 Index : 1;
  unsigned __int8 Processor : 5;
  unsigned __int8 Inserted : 1;
  unsigned __int8 Expired : 1;
};

/* 136 */
struct $DC5C26BDF4D684F12F3A5D4531D3B949
{
  unsigned __int8 QueueType;
  unsigned __int8 Timer2Flags;
  unsigned __int8 QueueSize;
  unsigned __int8 Timer2Reserved2;
};

/* 137 */
struct $82359CCE575330AAB08AF0894BC28AE0
{
  unsigned __int8 ThreadType;
  unsigned __int8 Timer2Inserted : 1;
  unsigned __int8 Timer2Expiring : 1;
  unsigned __int8 Timer2CancelPending : 1;
  unsigned __int8 Timer2SetPending : 1;
  unsigned __int8 Timer2Running : 1;
  unsigned __int8 Timer2Disabled : 1;
  unsigned __int8 Timer2ReservedFlags : 2;
  unsigned __int8 ThreadControlFlags;
  unsigned __int8 QueueReserved;
};

/* 138 */
struct $9300EC2846D44244344338BB8331DF4E
{
  unsigned __int8 MutantType;
  unsigned __int8 QueueControlFlags;
  unsigned __int8 CycleProfiling : 1;
  unsigned __int8 CounterProfiling : 1;
  unsigned __int8 GroupScheduling : 1;
  unsigned __int8 AffinitySet : 1;
  unsigned __int8 Tagged : 1;
  unsigned __int8 EnergyProfiling : 1;
  unsigned __int8 Instrumented : 1;
  unsigned __int8 ThreadReservedControlFlags : 1;
  unsigned __int8 DebugActive;
};

/* 139 */
struct $311232CAD4ECFA502922D62D223D90C0
{
  _BYTE gap0;
  unsigned __int8 Abandoned : 1;
  unsigned __int8 DisableIncrement : 1;
  unsigned __int8 QueueReservedControlFlags : 6;
  unsigned __int8 DpcActive;
  unsigned __int8 MutantReserved;
};

/* 140 */
struct $6287A180EBF0351F83293B36E60E22FF
{
  _BYTE gap0;
  unsigned __int8 ThreadReserved;
};

/* 141 */
struct $4B94A638C9572C40F7312179A2B431F6
{
  _BYTE gap0;
  unsigned __int8 MutantSize;
};

/* 142 */
union $484AD5298DFD2E3818D243F6A6039D2D
{
  volatile int Lock;
  int LockNV;
  $08481D05807C14C022C64127DBCB0DC5 __s2;
  $BDD1DEEA9085FB2031C94E38C028AF9F __s3;
  $1A64267CB6701B751C40AA7938D55A2C __s4;
  $DC5C26BDF4D684F12F3A5D4531D3B949 __s5;
  $82359CCE575330AAB08AF0894BC28AE0 __s6;
  $9300EC2846D44244344338BB8331DF4E __s7;
  $311232CAD4ECFA502922D62D223D90C0 __s8;
  $6287A180EBF0351F83293B36E60E22FF __s9;
  $4B94A638C9572C40F7312179A2B431F6 __s10;
};

/* 132 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 143 */
struct _DISPATCHER_HEADER
{
  $484AD5298DFD2E3818D243F6A6039D2D ___u0;
  int SignalState;
  _LIST_ENTRY WaitListHead;
};

/* 440 */
struct $B950AFB169DC87688B328897744C612F
{
  unsigned int LowPart;
  unsigned int HighPart;
};

/* 439 */
struct _ULARGE_INTEGER::<unnamed_type_u>
{
  unsigned int LowPart;
  unsigned int HighPart;
};

/* 441 */
union _ULARGE_INTEGER
{
  $B950AFB169DC87688B328897744C612F __s0;
  _ULARGE_INTEGER::<unnamed_type_u> u;
  unsigned __int64 QuadPart;
};

/* 558 */
struct _KTIMER
{
  _DISPATCHER_HEADER Header;
  _ULARGE_INTEGER DueTime;
  _LIST_ENTRY TimerListEntry;
  _KDPC *Dpc;
  unsigned int Period;
};

/* 251 */
struct $82623AFB470F8517B6D8F9E43441C7E1
{
  unsigned __int8 Type;
  unsigned __int8 Importance;
  volatile unsigned __int16 Number;
};

/* 252 */
union $F2E0A0BDC0C3231F020C9A1BE8B653A8
{
  unsigned int TargetInfoAsUlong;
  $82623AFB470F8517B6D8F9E43441C7E1 __s1;
};

/* 154 */
struct _SINGLE_LIST_ENTRY
{
  _SINGLE_LIST_ENTRY *Next;
};

/* 250 */
struct _KDPC
{
  $F2E0A0BDC0C3231F020C9A1BE8B653A8 ___u0;
  _SINGLE_LIST_ENTRY DpcListEntry;
  unsigned int ProcessorHistory;
  void (__stdcall *DeferredRoutine)(_KDPC *, void *, void *, void *);
  void *DeferredContext;
  void *SystemArgument1;
  void *SystemArgument2;
  void *DpcData;
};

/* 586 */
struct __declspec(align(4)) _HK_DEVICE_CONTEXT
{
  WDFDEVICE__ *Device;
  WDFQUEUE__ *Queue;
  VMBCHANNEL__ *Channel;
  void (__stdcall *ServiceRoutine)(void *, void *, void *, void *);
  _DEVICE_OBJECT *ServiceDevice;
  _KEYBOARD_ATTRIBUTES Attributes;
  _KEYBOARD_INDICATOR_PARAMETERS Indicators;
  unsigned __int8 ProtocolAccepted;
  _DV_RUNDOWN_BARRIER TimerRundown;
  _KTIMER Timer;
  _KDPC TimerDpc;
  unsigned int RingBufferOverflowThreshold;
  unsigned __int64 LastPacketReceivedTimeStamp;
  unsigned int PacketCount;
  _HK_CRASH_DUMP_FLAGS CrashFlags;
  _HK_CRASH_DUMP_FLAGS CurrentCrashFlags;
  unsigned __int8 CrashScanCode;
  unsigned __int8 CrashScanCode2;
};

/* 281 */
struct WDFDEVICE__
{
  int unused;
};

/* 270 */
struct WDFQUEUE__
{
  int unused;
};

/* 561 */
struct VMBCHANNEL__
{
  int unused;
};

/* 167 */
struct __declspec(align(4)) _KDEVICE_QUEUE_ENTRY
{
  _LIST_ENTRY DeviceListEntry;
  unsigned int SortKey;
  unsigned __int8 Inserted;
};

/* 253 */
struct $E1B98494FD87F330BB99E3FDFCE7D8B9
{
  _LIST_ENTRY DmaWaitEntry;
  unsigned int NumberOfChannels;
  unsigned __int32 SyncCallback : 1;
  unsigned __int32 DmaContext : 1;
  unsigned __int32 ZeroMapRegisters : 1;
  unsigned __int32 Reserved : 29;
};

/* 254 */
union $8C99E1C709D18C1A93362DD50E1AD07A
{
  _KDEVICE_QUEUE_ENTRY WaitQueueEntry;
  $E1B98494FD87F330BB99E3FDFCE7D8B9 __s1;
};

/* 35 */
enum _IO_ALLOCATION_ACTION : __int32
{
  KeepObject = 0x1,
  DeallocateObject = 0x2,
  DeallocateObjectKeepRegisters = 0x3,
};

/* 255 */
struct _WAIT_CONTEXT_BLOCK
{
  $8C99E1C709D18C1A93362DD50E1AD07A ___u0;
  _IO_ALLOCATION_ACTION (__stdcall *DeviceRoutine)(_DEVICE_OBJECT *, _IRP *, void *, void *);
  void *DeviceContext;
  unsigned int NumberOfMapRegisters;
  void *DeviceObject;
  void *CurrentIrp;
  _KDPC *BufferChainingDpc;
};

/* 256 */
union $9D33ECDDF105AB7098875B904CF8F20A
{
  _LIST_ENTRY ListEntry;
  _WAIT_CONTEXT_BLOCK Wcb;
};

/* 257 */
struct __declspec(align(4)) _KDEVICE_QUEUE
{
  __int16 Type;
  __int16 Size;
  _LIST_ENTRY DeviceListHead;
  unsigned int Lock;
  unsigned __int8 Busy;
};

/* 144 */
struct _KEVENT
{
  _DISPATCHER_HEADER Header;
};

/* 126 */
struct _DEVICE_OBJECT
{
  __int16 Type;
  unsigned __int16 Size;
  int ReferenceCount;
  _DRIVER_OBJECT *DriverObject;
  _DEVICE_OBJECT *NextDevice;
  _DEVICE_OBJECT *AttachedDevice;
  _IRP *CurrentIrp;
  struct _IO_TIMER *Timer;
  unsigned int Flags;
  unsigned int Characteristics;
  _VPB *Vpb;
  void *DeviceExtension;
  unsigned int DeviceType;
  char StackSize;
  $9D33ECDDF105AB7098875B904CF8F20A Queue;
  unsigned int AlignmentRequirement;
  _KDEVICE_QUEUE DeviceQueue;
  _KDPC Dpc;
  unsigned int ActiveThreadCount;
  void *SecurityDescriptor;
  _KEVENT DeviceLock;
  unsigned __int16 SectorSize;
  unsigned __int16 Spare1;
  _DEVOBJ_EXTENSION *DeviceObjectExtension;
  void *Reserved;
};

/* 580 */
struct _DV_RUNDOWN_BARRIER_WAIT_BLOCK
{
  int Counter;
  _KEVENT Event;
};

/* 600 */
typedef unsigned __int16 wchar_t;

/* 101 */
struct _UNICODE_STRING
{
  unsigned __int16 Length;
  unsigned __int16 MaximumLength;
  wchar_t *Buffer;
};

/* 127 */
struct _DRIVER_OBJECT
{
  __int16 Type;
  __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  unsigned int Flags;
  void *DriverStart;
  unsigned int DriverSize;
  void *DriverSection;
  _DRIVER_EXTENSION *DriverExtension;
  _UNICODE_STRING DriverName;
  _UNICODE_STRING *HardwareDatabase;
  _FAST_IO_DISPATCH *FastIoDispatch;
  int (__stdcall *DriverInit)(_DRIVER_OBJECT *, _UNICODE_STRING *);
  void (__stdcall *DriverStartIo)(_DEVICE_OBJECT *, _IRP *);
  void (__stdcall *DriverUnload)(_DRIVER_OBJECT *);
  int (__stdcall *MajorFunction[28])(_DEVICE_OBJECT *, _IRP *);
};

/* 163 */
union $8C74EF4479124B4DAD76BA7E20A1F8A3
{
  _IRP *MasterIrp;
  int IrpCount;
  void *SystemBuffer;
};

/* 146 */
union $250F5FE22B4503EFD7D48C86CC7F2167
{
  int Status;
  void *Pointer;
};

/* 147 */
struct _IO_STATUS_BLOCK
{
  $250F5FE22B4503EFD7D48C86CC7F2167 ___u0;
  unsigned int Information;
};

/* 164 */
union $DADDC7B06117AAA3B8C7D922A57DCF5A
{
  void (__stdcall *UserApcRoutine)(void *, _IO_STATUS_BLOCK *, unsigned int);
  void *IssuingProcess;
};

/* 165 */
struct $0AC40EC3E05F0A6251B596FE9138609D
{
  $DADDC7B06117AAA3B8C7D922A57DCF5A ___u0;
  void *UserApcContext;
};

/* 102 */
struct $FAF74743FBE1C8632047CFB668F7028A
{
  unsigned int LowPart;
  int HighPart;
};

/* 103 */
union _LARGE_INTEGER
{
  $FAF74743FBE1C8632047CFB668F7028A __s0;
  $FAF74743FBE1C8632047CFB668F7028A u;
  __int64 QuadPart;
};

/* 166 */
union $EE366BEB590EE6C44332A8C8F0A35756
{
  $0AC40EC3E05F0A6251B596FE9138609D AsynchronousParameters;
  _LARGE_INTEGER AllocationSize;
};

/* 244 */
union $E5663EAB11C48E60BF85E37FCB510CA5
{
  _KDEVICE_QUEUE_ENTRY DeviceQueueEntry;
  void *DriverContext[4];
};

/* 245 */
union $9848F2D897336AC13818E5844A297C68
{
  _IO_STACK_LOCATION *CurrentStackLocation;
  unsigned int PacketType;
};

/* 246 */
struct $D3C13497E6499C574DA74154775A3699
{
  $E5663EAB11C48E60BF85E37FCB510CA5 ___u0;
  struct _KTHREAD *Thread;
  char *AuxiliaryBuffer;
  _LIST_ENTRY ListEntry;
  $9848F2D897336AC13818E5844A297C68 ___u4;
  _FILE_OBJECT *OriginalFileObject;
};

/* 247 */
struct __declspec(align(2)) _KAPC
{
  unsigned __int8 Type;
  unsigned __int8 SpareByte0;
  unsigned __int8 Size;
  unsigned __int8 SpareByte1;
  unsigned int SpareLong0;
  struct _KTHREAD *Thread;
  _LIST_ENTRY ApcListEntry;
  void *Reserved[3];
  void *NormalContext;
  void *SystemArgument1;
  void *SystemArgument2;
  char ApcStateIndex;
  char ApcMode;
  unsigned __int8 Inserted;
};

/* 248 */
union $4A14F8E29AE40E4F633E644657784993
{
  $D3C13497E6499C574DA74154775A3699 Overlay;
  _KAPC Apc;
  void *CompletionKey;
};

/* 162 */
struct _IRP
{
  __int16 Type;
  unsigned __int16 Size;
  _MDL *MdlAddress;
  unsigned int Flags;
  $8C74EF4479124B4DAD76BA7E20A1F8A3 AssociatedIrp;
  _LIST_ENTRY ThreadListEntry;
  _IO_STATUS_BLOCK IoStatus;
  char RequestorMode;
  unsigned __int8 PendingReturned;
  char StackCount;
  char CurrentLocation;
  unsigned __int8 Cancel;
  unsigned __int8 CancelIrql;
  char ApcEnvironment;
  unsigned __int8 AllocationFlags;
  _IO_STATUS_BLOCK *UserIosb;
  _KEVENT *UserEvent;
  $EE366BEB590EE6C44332A8C8F0A35756 Overlay;
  void (__stdcall *CancelRoutine)(_DEVICE_OBJECT *, _IRP *);
  void *UserBuffer;
  $4A14F8E29AE40E4F633E644657784993 Tail;
};

/* 129 */
struct _VPB
{
  __int16 Type;
  __int16 Size;
  unsigned __int16 Flags;
  unsigned __int16 VolumeLabelLength;
  _DEVICE_OBJECT *DeviceObject;
  _DEVICE_OBJECT *RealDevice;
  unsigned int SerialNumber;
  unsigned int ReferenceCount;
  wchar_t VolumeLabel[32];
};

/* 258 */
struct _DEVOBJ_EXTENSION
{
  __int16 Type;
  unsigned __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  unsigned int PowerFlags;
  struct _DEVICE_OBJECT_POWER_EXTENSION *Dope;
  unsigned int ExtensionFlags;
  void *DeviceNode;
  _DEVICE_OBJECT *AttachedTo;
  int StartIoCount;
  int StartIoKey;
  unsigned int StartIoFlags;
  _VPB *Vpb;
  void *DependencyNode;
  void *InterruptContext;
  void *VerifierContext;
};

/* 128 */
struct _DRIVER_EXTENSION
{
  _DRIVER_OBJECT *DriverObject;
  int (__stdcall *AddDevice)(_DRIVER_OBJECT *, _DEVICE_OBJECT *);
  unsigned int Count;
  _UNICODE_STRING ServiceKeyName;
};

/* 249 */
struct _FAST_IO_DISPATCH
{
  unsigned int SizeOfFastIoDispatch;
  unsigned __int8 (__stdcall *FastIoCheckIfPossible)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, unsigned __int8, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoRead)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, void *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, void *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryBasicInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_BASIC_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryStandardInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_STANDARD_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoLock)(_FILE_OBJECT *, _LARGE_INTEGER *, _LARGE_INTEGER *, struct _KPROCESS *, unsigned int, unsigned __int8, unsigned __int8, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockSingle)(_FILE_OBJECT *, _LARGE_INTEGER *, _LARGE_INTEGER *, struct _KPROCESS *, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockAll)(_FILE_OBJECT *, struct _KPROCESS *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockAllByKey)(_FILE_OBJECT *, void *, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoDeviceControl)(_FILE_OBJECT *, unsigned __int8, void *, unsigned int, void *, unsigned int, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  void (__stdcall *AcquireFileForNtCreateSection)(_FILE_OBJECT *);
  void (__stdcall *ReleaseFileForNtCreateSection)(_FILE_OBJECT *);
  void (__stdcall *FastIoDetachDevice)(_DEVICE_OBJECT *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryNetworkOpenInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_NETWORK_OPEN_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  int (__stdcall *AcquireForModWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, _ERESOURCE **, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlRead)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, _MDL **, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlReadComplete)(_FILE_OBJECT *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *PrepareMdlWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, _MDL **, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlWriteComplete)(_FILE_OBJECT *, _LARGE_INTEGER *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoReadCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, void *, _MDL **, _IO_STATUS_BLOCK *, _COMPRESSED_DATA_INFO *, unsigned int, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoWriteCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, void *, _MDL **, _IO_STATUS_BLOCK *, _COMPRESSED_DATA_INFO *, unsigned int, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlReadCompleteCompressed)(_FILE_OBJECT *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlWriteCompleteCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryOpen)(_IRP *, _FILE_NETWORK_OPEN_INFORMATION *, _DEVICE_OBJECT *);
  int (__stdcall *ReleaseForModWrite)(_FILE_OBJECT *, _ERESOURCE *, _DEVICE_OBJECT *);
  int (__stdcall *AcquireForCcFlush)(_FILE_OBJECT *, _DEVICE_OBJECT *);
  int (__stdcall *ReleaseForCcFlush)(_FILE_OBJECT *, _DEVICE_OBJECT *);
};

/* 160 */
struct _MDL
{
  _MDL *Next;
  __int16 Size;
  __int16 MdlFlags;
  struct _EPROCESS *Process;
  void *MappedSystemVa;
  void *StartVa;
  unsigned int ByteCount;
  unsigned int ByteOffset;
};

/* 175 */
struct $B339F8CBA3EA44EDCCC66415E54F4C9B
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 FileAttributes;
  unsigned __int16 ShareAccess;
  unsigned int EaLength;
};

/* 177 */
struct $C97E83A60171B2C9C55B818275468DF9
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 Reserved;
  unsigned __int16 ShareAccess;
  _NAMED_PIPE_CREATE_PARAMETERS *Parameters;
};

/* 179 */
struct $1B46BFE6DF4A65BEA79D22ED652D2255
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 Reserved;
  unsigned __int16 ShareAccess;
  _MAILSLOT_CREATE_PARAMETERS *Parameters;
};

/* 180 */
struct $DA6BF238D2894862C121D4A81C48F68F
{
  unsigned int Length;
  unsigned int Key;
  _LARGE_INTEGER ByteOffset;
};

/* 47 */
enum _FILE_INFORMATION_CLASS : __int32
{
  FileDirectoryInformation = 0x1,
  FileFullDirectoryInformation = 0x2,
  FileBothDirectoryInformation = 0x3,
  FileBasicInformation = 0x4,
  FileStandardInformation = 0x5,
  FileInternalInformation = 0x6,
  FileEaInformation = 0x7,
  FileAccessInformation = 0x8,
  FileNameInformation = 0x9,
  FileRenameInformation = 0xA,
  FileLinkInformation = 0xB,
  FileNamesInformation = 0xC,
  FileDispositionInformation = 0xD,
  FilePositionInformation = 0xE,
  FileFullEaInformation = 0xF,
  FileModeInformation = 0x10,
  FileAlignmentInformation = 0x11,
  FileAllInformation = 0x12,
  FileAllocationInformation = 0x13,
  FileEndOfFileInformation = 0x14,
  FileAlternateNameInformation = 0x15,
  FileStreamInformation = 0x16,
  FilePipeInformation = 0x17,
  FilePipeLocalInformation = 0x18,
  FilePipeRemoteInformation = 0x19,
  FileMailslotQueryInformation = 0x1A,
  FileMailslotSetInformation = 0x1B,
  FileCompressionInformation = 0x1C,
  FileObjectIdInformation = 0x1D,
  FileCompletionInformation = 0x1E,
  FileMoveClusterInformation = 0x1F,
  FileQuotaInformation = 0x20,
  FileReparsePointInformation = 0x21,
  FileNetworkOpenInformation = 0x22,
  FileAttributeTagInformation = 0x23,
  FileTrackingInformation = 0x24,
  FileIdBothDirectoryInformation = 0x25,
  FileIdFullDirectoryInformation = 0x26,
  FileValidDataLengthInformation = 0x27,
  FileShortNameInformation = 0x28,
  FileIoCompletionNotificationInformation = 0x29,
  FileIoStatusBlockRangeInformation = 0x2A,
  FileIoPriorityHintInformation = 0x2B,
  FileSfioReserveInformation = 0x2C,
  FileSfioVolumeInformation = 0x2D,
  FileHardLinkInformation = 0x2E,
  FileProcessIdsUsingFileInformation = 0x2F,
  FileNormalizedNameInformation = 0x30,
  FileNetworkPhysicalNameInformation = 0x31,
  FileIdGlobalTxDirectoryInformation = 0x32,
  FileIsRemoteDeviceInformation = 0x33,
  FileUnusedInformation = 0x34,
  FileNumaNodeInformation = 0x35,
  FileStandardLinkInformation = 0x36,
  FileRemoteProtocolInformation = 0x37,
  FileRenameInformationBypassAccessCheck = 0x38,
  FileLinkInformationBypassAccessCheck = 0x39,
  FileVolumeNameInformation = 0x3A,
  FileIdInformation = 0x3B,
  FileIdExtdDirectoryInformation = 0x3C,
  FileReplaceCompletionInformation = 0x3D,
  FileHardLinkFullIdInformation = 0x3E,
  FileIdExtdBothDirectoryInformation = 0x3F,
  FileMaximumInformation = 0x40,
};

/* 181 */
struct $9A79A6625B506751C65F84AAE89A782B
{
  unsigned int Length;
  _UNICODE_STRING *FileName;
  _FILE_INFORMATION_CLASS FileInformationClass;
  unsigned int FileIndex;
};

/* 182 */
struct $50A7D1BFBD4B9BBEBCBBE3D92FEB6A61
{
  unsigned int Length;
  unsigned int CompletionFilter;
};

/* 183 */
struct $1C4A41907101204B2BA923D3CB031A2A
{
  unsigned int Length;
  _FILE_INFORMATION_CLASS FileInformationClass;
};

/* 184 */
struct $BBD6C80A82148A7CAD5B218A5A41C1D9
{
  unsigned __int8 ReplaceIfExists;
  unsigned __int8 AdvanceOnly;
};

/* 185 */
union $8FCDA4A03A95BC061A9294CF9F0D7955
{
  $BBD6C80A82148A7CAD5B218A5A41C1D9 __s0;
  unsigned int ClusterCount;
  void *DeleteHandle;
};

/* 186 */
struct $61439415B84408B622E4E4C831857686
{
  unsigned int Length;
  _FILE_INFORMATION_CLASS FileInformationClass;
  _FILE_OBJECT *FileObject;
  $8FCDA4A03A95BC061A9294CF9F0D7955 ___u3;
};

/* 187 */
struct $43049A1C9CD1076EE2F76BA56B9556D6
{
  unsigned int Length;
  void *EaList;
  unsigned int EaListLength;
  unsigned int EaIndex;
};

/* 188 */
struct $44CAF4394294FD1AA9144BF9A47D2B76
{
  unsigned int Length;
};

/* 40 */
enum _FSINFOCLASS : __int32
{
  FileFsVolumeInformation = 0x1,
  FileFsLabelInformation = 0x2,
  FileFsSizeInformation = 0x3,
  FileFsDeviceInformation = 0x4,
  FileFsAttributeInformation = 0x5,
  FileFsControlInformation = 0x6,
  FileFsFullSizeInformation = 0x7,
  FileFsObjectIdInformation = 0x8,
  FileFsDriverPathInformation = 0x9,
  FileFsVolumeFlagsInformation = 0xA,
  FileFsSectorSizeInformation = 0xB,
  FileFsDataCopyInformation = 0xC,
  FileFsMetadataSizeInformation = 0xD,
  FileFsMaximumInformation = 0xE,
};

/* 189 */
struct $074E5C494B75D5ABB8B4E15113411E3B
{
  unsigned int Length;
  _FSINFOCLASS FsInformationClass;
};

/* 190 */
struct $1452ECD7C6E5AB3C058EED8909EEC64B
{
  unsigned int OutputBufferLength;
  unsigned int InputBufferLength;
  unsigned int FsControlCode;
  void *Type3InputBuffer;
};

/* 191 */
struct $A51108C36F332C0078C3D055F4A33AD9
{
  _LARGE_INTEGER *Length;
  unsigned int Key;
  _LARGE_INTEGER ByteOffset;
};

/* 192 */
struct $343716E60DEC8CEA3C236115305CA9A5
{
  unsigned int OutputBufferLength;
  unsigned int InputBufferLength;
  unsigned int IoControlCode;
  void *Type3InputBuffer;
};

/* 193 */
struct $79FAFD50642EF9FCAC6F48CCDD5826D7
{
  unsigned int SecurityInformation;
  unsigned int Length;
};

/* 194 */
struct $29E784017BF8D630C3CED492840B3F1E
{
  unsigned int SecurityInformation;
  void *SecurityDescriptor;
};

/* 195 */
struct $07B69B37D9C3F1B028FB9DA10C914011
{
  _VPB *Vpb;
  _DEVICE_OBJECT *DeviceObject;
};

/* 196 */
struct $B2B4984C7002DD41520623255E2F9497
{
  struct _SCSI_REQUEST_BLOCK *Srb;
};

/* 200 */
struct $B7027E94ED4F360AB0769E14B2CE3771
{
  unsigned int Length;
  void *StartSid;
  _FILE_GET_QUOTA_INFORMATION *SidList;
  unsigned int SidListLength;
};

/* 59 */
enum _DEVICE_RELATION_TYPE : __int32
{
  BusRelations = 0x0,
  EjectionRelations = 0x1,
  PowerRelations = 0x2,
  RemovalRelations = 0x3,
  TargetDeviceRelation = 0x4,
  SingleBusRelations = 0x5,
  TransportRelations = 0x6,
};

/* 201 */
struct $DD666F4480444DE3EB7B8E73EE0E4BC1
{
  _DEVICE_RELATION_TYPE Type;
};

/* 203 */
struct $2978EE12A9E828BF6DFAF3DDD3B5277F
{
  const _GUID *InterfaceType;
  unsigned __int16 Size;
  unsigned __int16 Version;
  _INTERFACE *Interface;
  void *InterfaceSpecificData;
};

/* 205 */
struct $759EFCFBCE80F31F281DDD9A88A9B45B
{
  _DEVICE_CAPABILITIES *Capabilities;
};

/* 221 */
struct $DCDC0484674F7CFDB17ECB9FEFF1B075
{
  _IO_RESOURCE_REQUIREMENTS_LIST *IoResourceRequirementList;
};

/* 222 */
struct $5E4425892CB91929A7D567B5DA0A3F92
{
  unsigned int WhichSpace;
  void *Buffer;
  unsigned int Offset;
  unsigned int Length;
};

/* 223 */
struct $B367FCCFB95D7087158A479FE9C2D0D7
{
  unsigned __int8 Lock;
};

/* 67 */
enum BUS_QUERY_ID_TYPE : __int32
{
  BusQueryDeviceID = 0x0,
  BusQueryHardwareIDs = 0x1,
  BusQueryCompatibleIDs = 0x2,
  BusQueryInstanceID = 0x3,
  BusQueryDeviceSerialNumber = 0x4,
  BusQueryContainerID = 0x5,
};

/* 224 */
struct $52124CC28962514F8D2C971B61C58BA3
{
  BUS_QUERY_ID_TYPE IdType;
};

/* 58 */
enum DEVICE_TEXT_TYPE : __int32
{
  DeviceTextDescription = 0x0,
  DeviceTextLocationInformation = 0x1,
};

/* 225 */
struct $3FFB90D00B3582C74E3DCA267373351F
{
  DEVICE_TEXT_TYPE DeviceTextType;
  unsigned int LocaleId;
};

/* 49 */
enum _DEVICE_USAGE_NOTIFICATION_TYPE : __int32
{
  DeviceUsageTypeUndefined = 0x0,
  DeviceUsageTypePaging = 0x1,
  DeviceUsageTypeHibernation = 0x2,
  DeviceUsageTypeDumpFile = 0x3,
  DeviceUsageTypeBoot = 0x4,
  DeviceUsageTypePostDisplay = 0x5,
};

/* 226 */
struct $D76AB4AA9822D25EA2C85F666B4412C6
{
  unsigned __int8 InPath;
  unsigned __int8 Reserved[3];
  _DEVICE_USAGE_NOTIFICATION_TYPE Type;
};

/* 33 */
enum _SYSTEM_POWER_STATE : __int32
{
  PowerSystemUnspecified = 0x0,
  PowerSystemWorking = 0x1,
  PowerSystemSleeping1 = 0x2,
  PowerSystemSleeping2 = 0x3,
  PowerSystemSleeping3 = 0x4,
  PowerSystemHibernate = 0x5,
  PowerSystemShutdown = 0x6,
  PowerSystemMaximum = 0x7,
};

/* 227 */
struct $1E08BE435DE5F072445FF2D4B2FA847D
{
  _SYSTEM_POWER_STATE PowerState;
};

/* 229 */
struct $DCC568A5A8FE7D0038D0F51D6D8D6C41
{
  _POWER_SEQUENCE *PowerSequence;
};

/* 230 */
struct $76514DB155979F88E47E6F460A9859AB
{
  unsigned __int32 Reserved1 : 8;
  unsigned __int32 TargetSystemState : 4;
  unsigned __int32 EffectiveSystemState : 4;
  unsigned __int32 CurrentSystemState : 4;
  unsigned __int32 IgnoreHibernationPath : 1;
  unsigned __int32 PseudoTransition : 1;
  unsigned __int32 Reserved2 : 10;
};

/* 231 */
union $37904F79F8847849F0C79264A346334F
{
  $76514DB155979F88E47E6F460A9859AB __s0;
  unsigned int ContextAsUlong;
};

/* 232 */
struct _SYSTEM_POWER_STATE_CONTEXT
{
  $37904F79F8847849F0C79264A346334F ___u0;
};

/* 234 */
union $5A253A2AF09D456D40B73FCFEE5E6F6C
{
  unsigned int SystemContext;
  _SYSTEM_POWER_STATE_CONTEXT SystemPowerStateContext;
};

/* 39 */
enum _POWER_STATE_TYPE : __int32
{
  SystemPowerState = 0x0,
  DevicePowerState = 0x1,
};

/* 7 */
enum _DEVICE_POWER_STATE : __int32
{
  PowerDeviceUnspecified = 0x0,
  PowerDeviceD0 = 0x1,
  PowerDeviceD1 = 0x2,
  PowerDeviceD2 = 0x3,
  PowerDeviceD3 = 0x4,
  PowerDeviceMaximum = 0x5,
};

/* 233 */
union _POWER_STATE
{
  _SYSTEM_POWER_STATE SystemState;
  _DEVICE_POWER_STATE DeviceState;
};

/* 77 */
enum POWER_ACTION : __int32
{
  PowerActionNone = 0x0,
  PowerActionReserved = 0x1,
  PowerActionSleep = 0x2,
  PowerActionHibernate = 0x3,
  PowerActionShutdown = 0x4,
  PowerActionShutdownReset = 0x5,
  PowerActionShutdownOff = 0x6,
  PowerActionWarmEject = 0x7,
  PowerActionDisplayOff = 0x8,
};

/* 235 */
struct $97F2345F76C12D6A8EB696B24F8FA3F2
{
  $5A253A2AF09D456D40B73FCFEE5E6F6C ___u0;
  _POWER_STATE_TYPE Type;
  _POWER_STATE State;
  POWER_ACTION ShutdownType;
};

/* 239 */
struct $8950D28268AA474881C275E5E54AF8CC
{
  _CM_RESOURCE_LIST *AllocatedResources;
  _CM_RESOURCE_LIST *AllocatedResourcesTranslated;
};

/* 240 */
struct $27D1A893733DBE62F2FCC36974CB79FA
{
  unsigned int ProviderId;
  void *DataPath;
  unsigned int BufferSize;
  void *Buffer;
};

/* 241 */
struct $228F32E73A128818A25FF1959272C294
{
  void *Argument1;
  void *Argument2;
  void *Argument3;
  void *Argument4;
};

/* 242 */
union $86B586FD02EDCF82CBEDD66F57FB761E
{
  $B339F8CBA3EA44EDCCC66415E54F4C9B Create;
  $C97E83A60171B2C9C55B818275468DF9 CreatePipe;
  $1B46BFE6DF4A65BEA79D22ED652D2255 CreateMailslot;
  $DA6BF238D2894862C121D4A81C48F68F Read;
  $DA6BF238D2894862C121D4A81C48F68F Write;
  $9A79A6625B506751C65F84AAE89A782B QueryDirectory;
  $50A7D1BFBD4B9BBEBCBBE3D92FEB6A61 NotifyDirectory;
  $1C4A41907101204B2BA923D3CB031A2A QueryFile;
  $61439415B84408B622E4E4C831857686 SetFile;
  $43049A1C9CD1076EE2F76BA56B9556D6 QueryEa;
  $44CAF4394294FD1AA9144BF9A47D2B76 SetEa;
  $074E5C494B75D5ABB8B4E15113411E3B QueryVolume;
  $074E5C494B75D5ABB8B4E15113411E3B SetVolume;
  $1452ECD7C6E5AB3C058EED8909EEC64B FileSystemControl;
  $A51108C36F332C0078C3D055F4A33AD9 LockControl;
  $343716E60DEC8CEA3C236115305CA9A5 DeviceIoControl;
  $79FAFD50642EF9FCAC6F48CCDD5826D7 QuerySecurity;
  $29E784017BF8D630C3CED492840B3F1E SetSecurity;
  $07B69B37D9C3F1B028FB9DA10C914011 MountVolume;
  $07B69B37D9C3F1B028FB9DA10C914011 VerifyVolume;
  $B2B4984C7002DD41520623255E2F9497 Scsi;
  $B7027E94ED4F360AB0769E14B2CE3771 QueryQuota;
  $44CAF4394294FD1AA9144BF9A47D2B76 SetQuota;
  $DD666F4480444DE3EB7B8E73EE0E4BC1 QueryDeviceRelations;
  $2978EE12A9E828BF6DFAF3DDD3B5277F QueryInterface;
  $759EFCFBCE80F31F281DDD9A88A9B45B DeviceCapabilities;
  $DCDC0484674F7CFDB17ECB9FEFF1B075 FilterResourceRequirements;
  $5E4425892CB91929A7D567B5DA0A3F92 ReadWriteConfig;
  $B367FCCFB95D7087158A479FE9C2D0D7 SetLock;
  $52124CC28962514F8D2C971B61C58BA3 QueryId;
  $3FFB90D00B3582C74E3DCA267373351F QueryDeviceText;
  $D76AB4AA9822D25EA2C85F666B4412C6 UsageNotification;
  $1E08BE435DE5F072445FF2D4B2FA847D WaitWake;
  $DCC568A5A8FE7D0038D0F51D6D8D6C41 PowerSequence;
  $97F2345F76C12D6A8EB696B24F8FA3F2 Power;
  $8950D28268AA474881C275E5E54AF8CC StartDevice;
  $27D1A893733DBE62F2FCC36974CB79FA WMI;
  $228F32E73A128818A25FF1959272C294 Others;
};

/* 243 */
struct __unaligned __declspec(align(4)) _IO_STACK_LOCATION
{
  unsigned __int8 MajorFunction;
  unsigned __int8 MinorFunction;
  unsigned __int8 Flags;
  unsigned __int8 Control;
  $86B586FD02EDCF82CBEDD66F57FB761E Parameters;
  _DEVICE_OBJECT *DeviceObject;
  _FILE_OBJECT *FileObject;
  int (__stdcall *CompletionRoutine)(_DEVICE_OBJECT *, _IRP *, void *);
  void *Context;
};

/* 131 */
struct _FILE_OBJECT
{
  __int16 Type;
  __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  _VPB *Vpb;
  void *FsContext;
  void *FsContext2;
  _SECTION_OBJECT_POINTERS *SectionObjectPointer;
  void *PrivateCacheMap;
  int FinalStatus;
  _FILE_OBJECT *RelatedFileObject;
  unsigned __int8 LockOperation;
  unsigned __int8 DeletePending;
  unsigned __int8 ReadAccess;
  unsigned __int8 WriteAccess;
  unsigned __int8 DeleteAccess;
  unsigned __int8 SharedRead;
  unsigned __int8 SharedWrite;
  unsigned __int8 SharedDelete;
  unsigned int Flags;
  _UNICODE_STRING FileName;
  _LARGE_INTEGER CurrentByteOffset;
  unsigned int Waiters;
  unsigned int Busy;
  void *LastLock;
  _KEVENT Lock;
  _KEVENT Event;
  _IO_COMPLETION_CONTEXT *CompletionContext;
  unsigned int IrpListLock;
  _LIST_ENTRY IrpList;
  void *FileObjectExtension;
};

/* 148 */
struct __declspec(align(8)) _FILE_BASIC_INFORMATION
{
  _LARGE_INTEGER CreationTime;
  _LARGE_INTEGER LastAccessTime;
  _LARGE_INTEGER LastWriteTime;
  _LARGE_INTEGER ChangeTime;
  unsigned int FileAttributes;
};

/* 149 */
struct __declspec(align(4)) _FILE_STANDARD_INFORMATION
{
  _LARGE_INTEGER AllocationSize;
  _LARGE_INTEGER EndOfFile;
  unsigned int NumberOfLinks;
  unsigned __int8 DeletePending;
  unsigned __int8 Directory;
};

/* 150 */
struct __declspec(align(8)) _FILE_NETWORK_OPEN_INFORMATION
{
  _LARGE_INTEGER CreationTime;
  _LARGE_INTEGER LastAccessTime;
  _LARGE_INTEGER LastWriteTime;
  _LARGE_INTEGER ChangeTime;
  _LARGE_INTEGER AllocationSize;
  _LARGE_INTEGER EndOfFile;
  unsigned int FileAttributes;
};

/* 156 */
struct $9959C6898638794B7A02F04E7F980F81
{
  unsigned __int8 ReservedLowFlags;
  unsigned __int8 WaiterPriority;
};

/* 157 */
union $D738798313DD3A7A057854564DD59101
{
  unsigned __int16 Flag;
  $9959C6898638794B7A02F04E7F980F81 __s1;
};

/* 155 */
struct _KWAIT_CHAIN
{
  _SINGLE_LIST_ENTRY Head;
};

/* 151 */
struct $E71B718CD8428E7C8AA4A0868051E710
{
  unsigned __int32 IoPriorityBoosted : 1;
  unsigned __int32 OwnerReferenced : 1;
  unsigned __int32 IoQoSPriorityBoosted : 1;
  unsigned __int32 OwnerCount : 29;
};

/* 152 */
union $D02902373A192FB0A61376C0FA68AF2D
{
  $E71B718CD8428E7C8AA4A0868051E710 __s0;
  unsigned int TableSize;
};

/* 153 */
struct _OWNER_ENTRY
{
  unsigned int OwnerThread;
  $D02902373A192FB0A61376C0FA68AF2D ___u1;
};

/* 158 */
union $B8D4EB9E6E3D1A926634FE9A5064A2BB
{
  void *Address;
  unsigned int CreatorBackTraceIndex;
};

/* 159 */
struct _ERESOURCE
{
  _LIST_ENTRY SystemResourcesList;
  _OWNER_ENTRY *OwnerTable;
  __int16 ActiveCount;
  $D738798313DD3A7A057854564DD59101 ___u3;
  _KWAIT_CHAIN SharedWaiters;
  _KEVENT *ExclusiveWaiters;
  _OWNER_ENTRY OwnerEntry;
  unsigned int ActiveEntries;
  unsigned int ContentionCount;
  unsigned int NumberOfSharedWaiters;
  unsigned int NumberOfExclusiveWaiters;
  $B8D4EB9E6E3D1A926634FE9A5064A2BB ___u11;
  unsigned int SpinLock;
};

/* 161 */
struct _COMPRESSED_DATA_INFO
{
  unsigned __int16 CompressionFormatAndEngine;
  unsigned __int8 CompressionUnitShift;
  unsigned __int8 ChunkShift;
  unsigned __int8 ClusterShift;
  unsigned __int8 Reserved;
  unsigned __int16 NumberOfChunks;
  unsigned int CompressedChunkSizes[1];
};

/* 174 */
struct _IO_SECURITY_CONTEXT
{
  _SECURITY_QUALITY_OF_SERVICE *SecurityQos;
  _ACCESS_STATE *AccessState;
  unsigned int DesiredAccess;
  unsigned int FullCreateOptions;
};

/* 176 */
struct __declspec(align(8)) _NAMED_PIPE_CREATE_PARAMETERS
{
  unsigned int NamedPipeType;
  unsigned int ReadMode;
  unsigned int CompletionMode;
  unsigned int MaximumInstances;
  unsigned int InboundQuota;
  unsigned int OutboundQuota;
  _LARGE_INTEGER DefaultTimeout;
  unsigned __int8 TimeoutSpecified;
};

/* 178 */
struct __declspec(align(8)) _MAILSLOT_CREATE_PARAMETERS
{
  unsigned int MailslotQuota;
  unsigned int MaximumMessageSize;
  _LARGE_INTEGER ReadTimeout;
  unsigned __int8 TimeoutSpecified;
};

/* 197 */
struct _SID_IDENTIFIER_AUTHORITY
{
  unsigned __int8 Value[6];
};

/* 198 */
struct _SID
{
  unsigned __int8 Revision;
  unsigned __int8 SubAuthorityCount;
  _SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
  unsigned int SubAuthority[1];
};

/* 199 */
struct _FILE_GET_QUOTA_INFORMATION
{
  unsigned int NextEntryOffset;
  unsigned int SidLength;
  _SID Sid;
};

/* 96 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 202 */
struct _INTERFACE
{
  unsigned __int16 Size;
  unsigned __int16 Version;
  void *Context;
  void (__stdcall *InterfaceReference)(void *);
  void (__stdcall *InterfaceDereference)(void *);
};

/* 204 */
struct _DEVICE_CAPABILITIES
{
  unsigned __int16 Size;
  unsigned __int16 Version;
  unsigned __int32 DeviceD1 : 1;
  unsigned __int32 DeviceD2 : 1;
  unsigned __int32 LockSupported : 1;
  unsigned __int32 EjectSupported : 1;
  unsigned __int32 Removable : 1;
  unsigned __int32 DockDevice : 1;
  unsigned __int32 UniqueID : 1;
  unsigned __int32 SilentInstall : 1;
  unsigned __int32 RawDeviceOK : 1;
  unsigned __int32 SurpriseRemovalOK : 1;
  unsigned __int32 WakeFromD0 : 1;
  unsigned __int32 WakeFromD1 : 1;
  unsigned __int32 WakeFromD2 : 1;
  unsigned __int32 WakeFromD3 : 1;
  unsigned __int32 HardwareDisabled : 1;
  unsigned __int32 NonDynamic : 1;
  unsigned __int32 WarmEjectSupported : 1;
  unsigned __int32 NoDisplayInUI : 1;
  unsigned __int32 Reserved1 : 1;
  unsigned __int32 WakeFromInterrupt : 1;
  unsigned __int32 Reserved : 12;
  unsigned int Address;
  unsigned int UINumber;
  _DEVICE_POWER_STATE DeviceState[7];
  _SYSTEM_POWER_STATE SystemWake;
  _DEVICE_POWER_STATE DeviceWake;
  unsigned int D1Latency;
  unsigned int D2Latency;
  unsigned int D3Latency;
};

/* 38 */
enum _INTERFACE_TYPE : __int32
{
  InterfaceTypeUndefined = 0xFFFFFFFF,
  Internal = 0x0,
  Isa = 0x1,
  Eisa = 0x2,
  MicroChannel = 0x3,
  TurboChannel = 0x4,
  PCIBus = 0x5,
  VMEBus = 0x6,
  NuBus = 0x7,
  PCMCIABus = 0x8,
  CBus = 0x9,
  MPIBus = 0xA,
  MPSABus = 0xB,
  ProcessorInternal = 0xC,
  InternalPowerBus = 0xD,
  PNPISABus = 0xE,
  PNPBus = 0xF,
  Vmcs = 0x10,
  ACPIBus = 0x11,
  MaximumInterfaceType = 0x12,
};

/* 206 */
struct $F52C907EC7042149088B2180C08C425D
{
  unsigned int Length;
  unsigned int Alignment;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 80 */
enum _IRQ_DEVICE_POLICY : __int32
{
  IrqPolicyMachineDefault = 0x0,
  IrqPolicyAllCloseProcessors = 0x1,
  IrqPolicyOneCloseProcessor = 0x2,
  IrqPolicyAllProcessorsInMachine = 0x3,
  IrqPolicySpecifiedProcessors = 0x4,
  IrqPolicySpreadMessagesAcrossAllProcessors = 0x5,
};

/* 63 */
enum _IRQ_PRIORITY : __int32
{
  IrqPriorityUndefined = 0x0,
  IrqPriorityLow = 0x1,
  IrqPriorityNormal = 0x2,
  IrqPriorityHigh = 0x3,
};

/* 207 */
struct $61C0EEAC116F28C1EAA3287464544700
{
  unsigned int MinimumVector;
  unsigned int MaximumVector;
  _IRQ_DEVICE_POLICY AffinityPolicy;
  _IRQ_PRIORITY PriorityPolicy;
  unsigned int TargetedProcessors;
};

/* 208 */
struct $290D34FD7868E94AFEC0383C08CB9B28
{
  unsigned int MinimumChannel;
  unsigned int MaximumChannel;
};

/* 209 */
struct $66D8BAE383F9288207BB026A64AFF51A
{
  unsigned int RequestLine;
  unsigned int Reserved;
  unsigned int Channel;
  unsigned int TransferWidth;
};

/* 210 */
struct $B14DB811EDFC1214B110A98B000FF49B
{
  unsigned int Data[3];
};

/* 211 */
struct $CF7D779FCF8501AF42168A39ACA3AE76
{
  unsigned int Length;
  unsigned int MinBusNumber;
  unsigned int MaxBusNumber;
  unsigned int Reserved;
};

/* 212 */
struct $5D61DD2957AFDEE7ED67BD2EDF2BEA99
{
  unsigned int Priority;
  unsigned int Reserved1;
  unsigned int Reserved2;
};

/* 213 */
struct $FEB346262EA7C8ACE441ED57AA386338
{
  unsigned int Length40;
  unsigned int Alignment40;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 214 */
struct $23D53F49A52D7B52D55701D95105ABFC
{
  unsigned int Length48;
  unsigned int Alignment48;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 215 */
struct $4F138B2E4DD9164257FC8A10DF477646
{
  unsigned int Length64;
  unsigned int Alignment64;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 216 */
struct $EDAC022CDA01C704ED739E663C6F28A2
{
  unsigned __int8 Class;
  unsigned __int8 Type;
  unsigned __int8 Reserved1;
  unsigned __int8 Reserved2;
  unsigned int IdLowPart;
  unsigned int IdHighPart;
};

/* 217 */
union $A11E725142A760F4E4659C28CA58425D
{
  $F52C907EC7042149088B2180C08C425D Port;
  $F52C907EC7042149088B2180C08C425D Memory;
  $61C0EEAC116F28C1EAA3287464544700 Interrupt;
  $290D34FD7868E94AFEC0383C08CB9B28 Dma;
  $66D8BAE383F9288207BB026A64AFF51A DmaV3;
  $F52C907EC7042149088B2180C08C425D Generic;
  $B14DB811EDFC1214B110A98B000FF49B DevicePrivate;
  $CF7D779FCF8501AF42168A39ACA3AE76 BusNumber;
  $5D61DD2957AFDEE7ED67BD2EDF2BEA99 ConfigData;
  $FEB346262EA7C8ACE441ED57AA386338 Memory40;
  $23D53F49A52D7B52D55701D95105ABFC Memory48;
  $4F138B2E4DD9164257FC8A10DF477646 Memory64;
  $EDAC022CDA01C704ED739E663C6F28A2 Connection;
};

/* 218 */
struct _IO_RESOURCE_DESCRIPTOR
{
  unsigned __int8 Option;
  unsigned __int8 Type;
  unsigned __int8 ShareDisposition;
  unsigned __int8 Spare1;
  unsigned __int16 Flags;
  unsigned __int16 Spare2;
  $A11E725142A760F4E4659C28CA58425D u;
};

/* 219 */
struct _IO_RESOURCE_LIST
{
  unsigned __int16 Version;
  unsigned __int16 Revision;
  unsigned int Count;
  _IO_RESOURCE_DESCRIPTOR Descriptors[1];
};

/* 220 */
struct _IO_RESOURCE_REQUIREMENTS_LIST
{
  unsigned int ListSize;
  _INTERFACE_TYPE InterfaceType;
  unsigned int BusNumber;
  unsigned int SlotNumber;
  unsigned int Reserved[3];
  unsigned int AlternativeLists;
  _IO_RESOURCE_LIST List[1];
};

/* 228 */
struct _POWER_SEQUENCE
{
  unsigned int SequenceD1;
  unsigned int SequenceD2;
  unsigned int SequenceD3;
};

/* 104 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Generic>
{
  _LARGE_INTEGER Start;
  unsigned int Length;
};

/* 105 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Port>
{
  _LARGE_INTEGER Start;
  unsigned int Length;
};

/* 106 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Interrupt>
{
  unsigned int Level;
  unsigned int Vector;
  unsigned int Affinity;
};

/* 107 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt>::<unnamed_tag>::<unnamed_type_Raw>
{
  unsigned __int16 Reserved;
  unsigned __int16 MessageCount;
  unsigned int Vector;
  unsigned int Affinity;
};

/* 108 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt>::<unnamed_tag>::<unnamed_type_Translated>
{
  unsigned int Level;
  unsigned int Vector;
  unsigned int Affinity;
};

/* 109 */
union $4E6BD985018C8C1F37C97466D5B3B7A5
{
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt>::<unnamed_tag>::<unnamed_type_Raw> Raw;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt>::<unnamed_tag>::<unnamed_type_Translated> Translated;
};

/* 110 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt>
{
  $4E6BD985018C8C1F37C97466D5B3B7A5 ___u0;
};

/* 111 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory>
{
  _LARGE_INTEGER Start;
  unsigned int Length;
};

/* 112 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Dma>
{
  unsigned int Channel;
  unsigned int Port;
  unsigned int Reserved1;
};

/* 113 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DmaV3>
{
  unsigned int Channel;
  unsigned int RequestLine;
  unsigned __int8 TransferWidth;
  unsigned __int8 Reserved1;
  unsigned __int8 Reserved2;
  unsigned __int8 Reserved3;
};

/* 114 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DevicePrivate>
{
  unsigned int Data[3];
};

/* 115 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_BusNumber>
{
  unsigned int Start;
  unsigned int Length;
  unsigned int Reserved;
};

/* 116 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DeviceSpecificData>
{
  unsigned int DataSize;
  unsigned int Reserved1;
  unsigned int Reserved2;
};

/* 117 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory40>
{
  _LARGE_INTEGER Start;
  unsigned int Length40;
};

/* 118 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory48>
{
  _LARGE_INTEGER Start;
  unsigned int Length48;
};

/* 119 */
struct __unaligned __declspec(align(4)) _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory64>
{
  _LARGE_INTEGER Start;
  unsigned int Length64;
};

/* 120 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Connection>
{
  unsigned __int8 Class;
  unsigned __int8 Type;
  unsigned __int8 Reserved1;
  unsigned __int8 Reserved2;
  unsigned int IdLowPart;
  unsigned int IdHighPart;
};

/* 121 */
union _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>
{
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Generic> Generic;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Port> Port;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Interrupt> Interrupt;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_MessageInterrupt> MessageInterrupt;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory> Memory;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Dma> Dma;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DmaV3> DmaV3;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DevicePrivate> DevicePrivate;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_BusNumber> BusNumber;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_DeviceSpecificData> DeviceSpecificData;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory40> Memory40;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory48> Memory48;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Memory64> Memory64;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u>::<unnamed_type_Connection> Connection;
};

/* 122 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR
{
  unsigned __int8 Type;
  unsigned __int8 ShareDisposition;
  unsigned __int16 Flags;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR::<unnamed_type_u> u;
};

/* 236 */
struct _CM_PARTIAL_RESOURCE_LIST
{
  unsigned __int16 Version;
  unsigned __int16 Revision;
  unsigned int Count;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR PartialDescriptors[1];
};

/* 237 */
struct _CM_FULL_RESOURCE_DESCRIPTOR
{
  _INTERFACE_TYPE InterfaceType;
  unsigned int BusNumber;
  _CM_PARTIAL_RESOURCE_LIST PartialResourceList;
};

/* 238 */
struct _CM_RESOURCE_LIST
{
  unsigned int Count;
  _CM_FULL_RESOURCE_DESCRIPTOR List[1];
};

/* 130 */
struct _SECTION_OBJECT_POINTERS
{
  void *DataSectionObject;
  void *SharedCacheMap;
  void *ImageSectionObject;
};

/* 145 */
struct _IO_COMPLETION_CONTEXT
{
  void *Port;
  void *Key;
};

/* 36 */
enum _SECURITY_IMPERSONATION_LEVEL : __int32
{
  SecurityAnonymous = 0x0,
  SecurityIdentification = 0x1,
  SecurityImpersonation = 0x2,
  SecurityDelegation = 0x3,
};

/* 168 */
struct __declspec(align(4)) _SECURITY_QUALITY_OF_SERVICE
{
  unsigned int Length;
  _SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  unsigned __int8 ContextTrackingMode;
  unsigned __int8 EffectiveOnly;
};

/* 123 */
struct _LUID
{
  unsigned int LowPart;
  int HighPart;
};

/* 169 */
struct _SECURITY_SUBJECT_CONTEXT
{
  void *ClientToken;
  _SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  void *PrimaryToken;
  void *ProcessAuditId;
};

/* 124 */
struct _LUID_AND_ATTRIBUTES
{
  _LUID Luid;
  unsigned int Attributes;
};

/* 170 */
struct _INITIAL_PRIVILEGE_SET
{
  unsigned int PrivilegeCount;
  unsigned int Control;
  _LUID_AND_ATTRIBUTES Privilege[3];
};

/* 171 */
struct _PRIVILEGE_SET
{
  unsigned int PrivilegeCount;
  unsigned int Control;
  _LUID_AND_ATTRIBUTES Privilege[1];
};

/* 172 */
union $E74398192F082573DCDF8FA052EDE59E
{
  _INITIAL_PRIVILEGE_SET InitialPrivilegeSet;
  _PRIVILEGE_SET PrivilegeSet;
};

/* 173 */
struct _ACCESS_STATE
{
  _LUID OperationID;
  unsigned __int8 SecurityEvaluated;
  unsigned __int8 GenerateAudit;
  unsigned __int8 GenerateOnClose;
  unsigned __int8 PrivilegesAllocated;
  unsigned int Flags;
  unsigned int RemainingDesiredAccess;
  unsigned int PreviouslyGrantedAccess;
  unsigned int OriginalDesiredAccess;
  _SECURITY_SUBJECT_CONTEXT SubjectSecurityContext;
  void *SecurityDescriptor;
  void *AuxData;
  $E74398192F082573DCDF8FA052EDE59E Privileges;
  unsigned __int8 AuditPrivileges;
  _UNICODE_STRING ObjectName;
  _UNICODE_STRING ObjectTypeName;
};

/* 889 */
typedef _HK_DEVICE_CONTEXT *PHK_DEVICE_CONTEXT;

/* 1190 */
typedef _HK_DEVICE_CONTEXT *WDF_POINTER_TYPE_HK_DEVICE_CONTEXT;
