/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'netvsc.sys'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _MDL;
struct _SCATTER_GATHER_LIST;
struct WDFDEVICE__;
struct _NET_BUFFER_LIST;
struct _NET_BUFFER;
struct _NET_BUFFER_SHARED_MEMORY;
struct _NET_BUFFER_LIST_CONTEXT;
struct _RM_RNDIS_SUBALLOCATION_CONTEXT;
struct VMBCHANNEL__;
struct _NVSC_PDBM_DOMAIN;
struct _NVSC_SUPPLEMENTAL_SEND_BUFFER_SECTION;
struct VMBPACKETCOMPLETION__;
struct _NVSC_MICROPORT_CONTEXT;
struct _NVSC_V1_SEND_BUFFER_SECTION;
struct VMBPACKET__;

/* 440 */
struct $FAF74743FBE1C8632047CFB668F7028A
{
  unsigned int LowPart;
  int HighPart;
};

/* 441 */
union _LARGE_INTEGER
{
  $FAF74743FBE1C8632047CFB668F7028A __s0;
  $FAF74743FBE1C8632047CFB668F7028A u;
  __int64 QuadPart;
};

/* 1182 */
struct _NVSC_VMBUS_CHANNEL_INFO
{
  VMBCHANNEL__ *VmbChannel;
  _NVSC_MICROPORT_CONTEXT *MicroportContext;
  unsigned __int16 ChannelIndex;
  unsigned int PacketSize;
  unsigned __int8 IsReady;
  unsigned int ProcessorIndex;
  unsigned int PdQueueId;
};

/* 1183 */
struct _NVSC_RSS_INFO
{
  struct _NDIS_RW_LOCK_EX *RWLock;
  unsigned int HashType;
  unsigned int HashFunction;
  unsigned __int8 IsRssReady;
  unsigned int *QueueTable;
  unsigned __int16 QueueTableCount;
  unsigned int SendIndirectionTable[16];
};

/* 137 */
enum _NVSC_STATE : __int32
{
  NvscStateNone = 0x1,
  NvscStateWaitingForOpen = 0x2,
  NvscStateInitializing = 0x3,
  NvscStateOperational = 0x4,
  NvscStateMax = 0x5,
  NvscStateInvalid = 0xFFFFFFFF,
};

/* 471 */
struct $08481D05807C14C022C64127DBCB0DC5
{
  unsigned __int8 Type;
  unsigned __int8 Signalling;
  unsigned __int8 Size;
  unsigned __int8 Reserved1;
};

/* 472 */
struct $BDD1DEEA9085FB2031C94E38C028AF9F
{
  unsigned __int8 TimerType;
  unsigned __int8 TimerControlFlags;
  unsigned __int8 Hand;
  unsigned __int8 TimerMiscFlags;
};

/* 473 */
struct $1A64267CB6701B751C40AA7938D55A2C
{
  unsigned __int8 Timer2Type;
  unsigned __int8 Absolute : 1;
  unsigned __int8 Wake : 1;
  unsigned __int8 EncodedTolerableDelay : 6;
  unsigned __int8 Timer2Reserved1;
  unsigned __int8 Index : 1;
  unsigned __int8 Processor : 5;
  unsigned __int8 Inserted : 1;
  unsigned __int8 Expired : 1;
};

/* 474 */
struct $DC5C26BDF4D684F12F3A5D4531D3B949
{
  unsigned __int8 QueueType;
  unsigned __int8 Timer2Flags;
  unsigned __int8 QueueSize;
  unsigned __int8 Timer2Reserved2;
};

/* 475 */
struct $82359CCE575330AAB08AF0894BC28AE0
{
  unsigned __int8 ThreadType;
  unsigned __int8 Timer2Inserted : 1;
  unsigned __int8 Timer2Expiring : 1;
  unsigned __int8 Timer2CancelPending : 1;
  unsigned __int8 Timer2SetPending : 1;
  unsigned __int8 Timer2Running : 1;
  unsigned __int8 Timer2Disabled : 1;
  unsigned __int8 Timer2ReservedFlags : 2;
  unsigned __int8 ThreadControlFlags;
  unsigned __int8 QueueReserved;
};

/* 476 */
struct $9300EC2846D44244344338BB8331DF4E
{
  unsigned __int8 MutantType;
  unsigned __int8 QueueControlFlags;
  unsigned __int8 CycleProfiling : 1;
  unsigned __int8 CounterProfiling : 1;
  unsigned __int8 GroupScheduling : 1;
  unsigned __int8 AffinitySet : 1;
  unsigned __int8 Tagged : 1;
  unsigned __int8 EnergyProfiling : 1;
  unsigned __int8 Instrumented : 1;
  unsigned __int8 ThreadReservedControlFlags : 1;
  unsigned __int8 DebugActive;
};

/* 477 */
struct $311232CAD4ECFA502922D62D223D90C0
{
  _BYTE gap0;
  unsigned __int8 Abandoned : 1;
  unsigned __int8 DisableIncrement : 1;
  unsigned __int8 QueueReservedControlFlags : 6;
  unsigned __int8 DpcActive;
  unsigned __int8 MutantReserved;
};

/* 478 */
struct $6287A180EBF0351F83293B36E60E22FF
{
  _BYTE gap0;
  unsigned __int8 ThreadReserved;
};

/* 479 */
struct $4B94A638C9572C40F7312179A2B431F6
{
  _BYTE gap0;
  unsigned __int8 MutantSize;
};

/* 480 */
union $8F645015FE61CF6A2ACBB71C18B5AF94
{
  volatile int Lock;
  int LockNV;
  $08481D05807C14C022C64127DBCB0DC5 __s2;
  $BDD1DEEA9085FB2031C94E38C028AF9F __s3;
  $1A64267CB6701B751C40AA7938D55A2C __s4;
  $DC5C26BDF4D684F12F3A5D4531D3B949 __s5;
  $82359CCE575330AAB08AF0894BC28AE0 __s6;
  $9300EC2846D44244344338BB8331DF4E __s7;
  $311232CAD4ECFA502922D62D223D90C0 __s8;
  $6287A180EBF0351F83293B36E60E22FF __s9;
  $4B94A638C9572C40F7312179A2B431F6 __s10;
};

/* 470 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 481 */
struct _DISPATCHER_HEADER
{
  $8F645015FE61CF6A2ACBB71C18B5AF94 ___u0;
  int SignalState;
  _LIST_ENTRY WaitListHead;
};

/* 482 */
struct _KEVENT
{
  _DISPATCHER_HEADER Header;
};

/* 492 */
struct _SINGLE_LIST_ENTRY
{
  _SINGLE_LIST_ENTRY *Next;
};

/* 727 */
struct $A599625B7CDE08746C6A6D801F590169
{
  _SINGLE_LIST_ENTRY Next;
  unsigned __int16 Depth;
  unsigned __int16 CpuId;
};

/* 728 */
union _SLIST_HEADER
{
  unsigned __int64 Alignment;
  $A599625B7CDE08746C6A6D801F590169 __s1;
};

/* 1188 */
struct __declspec(align(8)) _NVSC_V1_CONTEXT
{
  unsigned int ReceiveBufferSize;
  void *ReceiveBuffer;
  unsigned int ReceiveBufferGpadlHandle;
  unsigned int NumReceiveBufferSections;
  _NVSP_1_RECEIVE_BUFFER_SECTION *ReceiveBufferSections;
  _RM_RNDIS_SUBALLOCATION_CONTEXT **ReceiveBufferSectionArray;
  unsigned int SendBufferSize;
  void *SendBuffer;
  unsigned int SendBufferGpadlHandle;
  unsigned int SendBufferSectionSize;
  _NVSC_V1_SEND_BUFFER_SECTION *SendBufferSections;
  _SLIST_HEADER SendBufferSectionsListHead;
  unsigned __int8 SendBufferCompleteSuccessful;
  unsigned __int8 Halting;
  VMBPACKET__ *ReceiveBuffersDeletePacket;
  VMBPACKET__ *SendBuffersDeletePacket;
};

/* 1189 */
struct _NVSC_V2_CONTEXT
{
  void *ReceiveNblPool;
};

/* 901 */
struct __declspec(align(8)) _NDIS_PD_CONFIG
{
  _NDIS_OBJECT_HEADER Header;
  unsigned int Flags;
  unsigned __int8 Enabled;
  unsigned int CapabilitiesOffset;
  unsigned int CapabilitiesSize;
};

/* 902 */
struct __declspec(align(8)) _NDIS_PD_CAPABILITIES
{
  _NDIS_OBJECT_HEADER Header;
  unsigned int Flags;
  unsigned int MaximumTxPartialBufferCount;
  unsigned int MaximumRxPartialBufferCount;
  unsigned __int8 RxFilterContextWidth;
  unsigned int CapabilityFlags;
  unsigned int MaxNumberOfRxQueues;
  unsigned int MaxNumberOfTxQueues;
  unsigned int MaxNumberOfRxQueuesForDefaultVport;
  unsigned int MaxNumberOfTxQueuesForDefaultVport;
  unsigned int MaxNumberOfRxQueuesPerNonDefaultVport;
  unsigned int MaxNumberOfTxQueuesPerNonDefaultVport;
  unsigned int ExactMatchProfileArrayOffset;
  unsigned int ExactMatchProfileArrayNumElements;
  unsigned int ExactMatchProfileArrayElementSize;
  unsigned int WildcardMatchProfileArrayOffset;
  unsigned int WildcardMatchProfileArrayNumElements;
  unsigned int WildcardMatchProfileArrayElementSize;
  unsigned int MinimumModerationInterval;
  unsigned int MaximumModerationInterval;
  unsigned int ModerationIntervalGranularity;
  unsigned int MaxRxQueueSize;
  unsigned int MaxTxQueueSize;
};

/* 1162 */
struct _NVSC_PD_CONFIG
{
  _NDIS_PD_CONFIG Configuration;
  _NDIS_PD_CAPABILITIES Capabilities;
};

/* 1190 */
struct __declspec(align(8)) _NVSC_PD_ADAPTER_CONTEXT
{
  void *MiniportAdapterHandle;
  _NVSC_PD_CONFIG Cfg;
  _NVSC_PDBM_DOMAIN *Domain;
  unsigned int DomainId;
  unsigned __int8 IsVmAdminEnabled;
  unsigned __int8 IsSupportedByVSP;
  unsigned __int8 IsEnabledByVSP;
  unsigned __int8 IsInitialized;
  volatile char IsPacketDirectEnabled;
  struct _NDIS_RW_LOCK_EX *ProviderListLock;
  _LIST_ENTRY ProviderList;
  unsigned int NumReceiveRssPDQueues;
  unsigned int NumPdQueues;
  _NVSC_VMBUS_CHANNEL_INFO *PdSubChannels;
  _LARGE_INTEGER MmioPhysicalAddress;
  unsigned int MmioLength;
  volatile __int64 QueueIdBitmap;
  void *Queue[64];
  struct _NDIS_RW_LOCK_EX *GroupListLock;
  _LIST_ENTRY GroupList;
};

/* 1181 */
struct _NVSC_MICROPORT_CONTEXT
{
  void *NdisMiniportHandle;
  void *MiniportAdapterContext;
  WDFDEVICE__ *WdfMiniportDevice;
  _NVSC_VMBUS_CHANNEL_INFO PrimaryChannel;
  _NVSC_VMBUS_CHANNEL_INFO *SubChannels;
  unsigned int NumSubChannels;
  _NVSC_RSS_INFO RssInfo;
  unsigned int *RssProcessorIndexs;
  unsigned int RssProcessorCount;
  _NVSC_STATE CurrentState;
  _KEVENT InitEvent;
  _KEVENT PnpSurpriseRemoveEvent;
  _KEVENT KmclInternalErrorEvent;
  unsigned int RequestedProtocolVersion;
  unsigned int ProtocolVersion;
  unsigned int NumIncomingMessageHandlers;
  unsigned int MinimumMessageSize;
  void (__stdcall **IncomingMessageHandlers)(_NVSC_MICROPORT_CONTEXT *, _NVSP_MESSAGE *, unsigned int, VMBPACKETCOMPLETION__ *);
  unsigned int MaximumMdlChainLength;
  volatile unsigned int NumOutstandingReceivedPackets;
  unsigned int NumPagesInIncomingRingBuffer;
  unsigned int NumPagesInOutgoingRingBuffer;
  unsigned int InterruptLatency;
  unsigned int MaxRndisMessageSize;
  unsigned int MaxNumOutstandingPackets;
  _NVSC_V1_CONTEXT Version1Data;
  _NVSC_V2_CONTEXT Version2Data;
  unsigned int MaxDataSize;
  unsigned int SupplementalSendBufferSize;
  void *SupplementalSendBuffer;
  _NVSC_SUPPLEMENTAL_SEND_BUFFER_SECTION *SupplementalSendBufferSections;
  _SLIST_HEADER SupplementalSendBuffersListHead;
  unsigned __int8 RequireSendBuffer;
  _NVSC_PD_ADAPTER_CONTEXT PdContext;
};

/* 615 */
struct WDFDEVICE__
{
  int unused;
};

/* 1104 */
struct VMBCHANNEL__
{
  int unused;
};

/* 1179 */
struct VMBPACKETCOMPLETION__
{
  int unused;
};

/* 1102 */
struct _RM_RNDIS_SUBALLOCATION_CONTEXT
{
  _MDL *Mdl;
  _NET_BUFFER_LIST *NetBufferList;
};

/* 1186 */
struct _NVSC_V1_SEND_BUFFER_SECTION
{
  _SINGLE_LIST_ENTRY SListEntry;
  void *Buffer;
  unsigned int Index;
};

/* 1187 */
struct VMBPACKET__
{
  int unused;
};

/* 1173 */
struct _NVSC_SUPPLEMENTAL_SEND_BUFFER_SECTION
{
  _SINGLE_LIST_ENTRY SListEntry;
  void *Buffer;
  _MDL *mdl;
};

/* 1170 */
struct _NVSC_PDBM_DOMAIN
{
  unsigned int Signature;
  unsigned int Id;
  _LIST_ENTRY DomainListEntry;
  void *MiniportAdapterContext;
  _LIST_ENTRY RegionList;
};

/* 498 */
struct _MDL
{
  _MDL *Next;
  __int16 Size;
  __int16 MdlFlags;
  struct _EPROCESS *Process;
  void *MappedSystemVa;
  void *StartVa;
  unsigned int ByteCount;
  unsigned int ByteOffset;
};

/* 887 */
struct $BD5759AA8011C0271A9ED90F6E9A9154
{
  _NET_BUFFER_LIST *Next;
  _NET_BUFFER *FirstNetBuffer;
};

/* 888 */
union _NET_BUFFER_LIST_HEADER
{
  $BD5759AA8011C0271A9ED90F6E9A9154 __s0;
  _SLIST_HEADER Link;
};

/* 890 */
union $D9E54647CB76507D8B6789EB223F7943
{
  $BD5759AA8011C0271A9ED90F6E9A9154 __s0;
  _SLIST_HEADER Link;
  _NET_BUFFER_LIST_HEADER NetBufferListHeader;
};

/* 891 */
union $C5ADD1FF3FF13D2C674FA6825D7C68A2
{
  int Status;
  unsigned int NdisReserved2;
};

/* 879 */
struct _NET_BUFFER_LIST
{
  $D9E54647CB76507D8B6789EB223F7943 ___u0;
  _NET_BUFFER_LIST_CONTEXT *Context;
  _NET_BUFFER_LIST *ParentNetBufferList;
  void *NdisPoolHandle;
  __declspec(align(8)) void *NdisReserved[2];
  void *ProtocolReserved[4];
  void *MiniportReserved[2];
  void *Scratch;
  void *SourceHandle;
  unsigned int NblFlags;
  int ChildRefCount;
  unsigned int Flags;
  $C5ADD1FF3FF13D2C674FA6825D7C68A2 ___u12;
  void *NetBufferListInfo[21];
};

/* 881 */
struct $BDC63944430D65BDF65D0425DB610F23
{
  _NET_BUFFER *Next;
  _MDL *CurrentMdl;
  unsigned int CurrentMdlOffset;
  unsigned int DataLength;
  _MDL *MdlChain;
  unsigned int DataOffset;
};

/* 882 */
struct $74083188D6CA37C4C5CC6CD1BB05D605
{
  _SLIST_HEADER Link;
  _BYTE gap8[4];
  unsigned int stDataLength;
};

/* 883 */
union _NET_BUFFER_HEADER
{
  $BDC63944430D65BDF65D0425DB610F23 __s0;
  $74083188D6CA37C4C5CC6CD1BB05D605 __s1;
};

/* 885 */
union $B197ACCDCC4484C7563D9C7A667DFEB1
{
  $BDC63944430D65BDF65D0425DB610F23 __s0;
  $74083188D6CA37C4C5CC6CD1BB05D605 __s1;
  _NET_BUFFER_HEADER NetBufferHeader;
};

/* 886 */
union $A519A699746C8798E1678032E1EC4876
{
  _NET_BUFFER_SHARED_MEMORY *SharedMemoryInfo;
  _SCATTER_GATHER_LIST *ScatterGatherList;
};

/* 880 */
struct __declspec(align(8)) _NET_BUFFER
{
  $B197ACCDCC4484C7563D9C7A667DFEB1 ___u0;
  unsigned __int16 ChecksumBias;
  unsigned __int16 Reserved;
  void *NdisPoolHandle;
  void *NdisReserved[2];
  void *ProtocolReserved[6];
  void *MiniportReserved[4];
  _LARGE_INTEGER DataPhysicalAddress;
  $A519A699746C8798E1678032E1EC4876 ___u8;
};

/* 889 */
struct _NET_BUFFER_LIST_CONTEXT
{
  _NET_BUFFER_LIST_CONTEXT *Next;
  unsigned __int16 Size;
  unsigned __int16 Offset;
  unsigned __int8 ContextData[];
};

/* 884 */
struct _NET_BUFFER_SHARED_MEMORY
{
  _NET_BUFFER_SHARED_MEMORY *NextSharedMemorySegment;
  unsigned int SharedMemoryFlags;
  void *SharedMemoryHandle;
  unsigned int SharedMemoryOffset;
  unsigned int SharedMemoryLength;
};

/* 593 */
struct _SCATTER_GATHER_ELEMENT
{
  _LARGE_INTEGER Address;
  unsigned int Length;
  unsigned int Reserved;
};

/* 594 */
struct _SCATTER_GATHER_LIST
{
  unsigned int NumberOfElements;
  unsigned int Reserved;
  _SCATTER_GATHER_ELEMENT Elements[];
};

/* 1197 */
struct NVSC_PROTOCOL_VERSION
{
  unsigned int ProtocolVersion;
  unsigned int NumIncomingMessageHandlers;
  unsigned int MinimumMessageSize;
  void (__stdcall **IncomingMessageHandlers)(_NVSC_MICROPORT_CONTEXT *, _NVSP_MESSAGE *, unsigned int, VMBPACKETCOMPLETION__ *);
};

/* 1202 */
struct $7F922323ADB25EB999A6CD37668EE709
{
  _KEVENT *Event;
  _NVSP_6_MESSAGE_PD_API_COMPLETE *CompletionInfo;
};

/* 1203 */
struct $C5CDF9D86B5DD0A4ACBBB31849839131
{
  void *PDQueue;
  _NVSP_6_MESSAGE_PD_BATCH_MESSAGE *Message;
};

/* 1335 */
struct _NVSP_SEND_INDIRECTION_TABLE_MESSAGE
{
  _NVSP_MESSAGE NvspMessage;
  unsigned int SendIndirectionTable[16];
};

/* 1836 */
struct _NVSP_TRANSFER_PAGE_RANGE
{
  unsigned __int64 TransferPageSetId;
  unsigned int ByteCount;
  unsigned int ByteOffset;
};

/* 3098 */
typedef _NVSP_TRANSFER_PAGE_RANGE *PNVSP_TRANSFER_PAGE_RANGE;

/* 5455 */
typedef void (__stdcall *PFN_HANDLE_INCOMING_MESSAGE)(_NVSC_MICROPORT_CONTEXT *, _NVSP_MESSAGE *, unsigned int, VMBPACKETCOMPLETION__ *);

/* 6792 */
typedef _NVSP_SEND_INDIRECTION_TABLE_MESSAGE *PNVSP_SEND_INDIRECTION_TABLE_MESSAGE;

