/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'storvsc.sys'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _DEVICE_OBJECT;
struct _DRIVER_OBJECT;
struct _DRIVER_EXTENSION;
struct _FILE_OBJECT;
struct _FILE_BASIC_INFORMATION;
struct _FILE_STANDARD_INFORMATION;
struct _FILE_NETWORK_OPEN_INFORMATION;
struct _OWNER_ENTRY;
struct _KEVENT;
struct _ERESOURCE;
struct _MDL;
struct _COMPRESSED_DATA_INFO;
struct _IRP;
struct _SECURITY_QUALITY_OF_SERVICE;
struct _ACCESS_STATE;
struct _IO_SECURITY_CONTEXT;
struct _NAMED_PIPE_CREATE_PARAMETERS;
struct _MAILSLOT_CREATE_PARAMETERS;
struct _VPB;
struct _SCSI_REQUEST_BLOCK;
struct _FILE_GET_QUOTA_INFORMATION;
struct _INTERFACE;
struct _DEVICE_CAPABILITIES;
struct _IO_RESOURCE_REQUIREMENTS_LIST;
struct _POWER_SEQUENCE;
struct _CM_RESOURCE_LIST;
struct _IO_STACK_LOCATION;
struct _FAST_IO_DISPATCH;
struct _KDPC;
struct _DEVOBJ_EXTENSION;
struct _SECTION_OBJECT_POINTERS;
struct _IO_COMPLETION_CONTEXT;
struct VMBCHANNEL__;
struct _VSTOR_CHANNEL_ETW_TRACE_INFO;
struct _STOR_CHANNEL_PROCESSOR_INFO;

/* 348 */
union $9A3AC779B8C5F2EFE3F1D75AB1834BA5
{
  _SCSI_REQUEST_BLOCK *Srb;
  _KEVENT *Event;
};

/* 346 */
struct _VSTOR_CHANNEL_REQUEST
{
  _MDL *Mdl;
  void (__stdcall *CompletionRoutine)(VMBCHANNEL__ *, VSTOR_PACKET_OPERATION, _VSTOR_PACKET *, _VSTOR_CHANNEL_REQUEST *);
  _VSTOR_CHANNEL_ETW_TRACE_INFO *EtwTraceInfo;
  $9A3AC779B8C5F2EFE3F1D75AB1834BA5 ___u3;
};

/* 122 */
struct _MDL
{
  _MDL *Next;
  __int16 Size;
  __int16 MdlFlags;
  struct _EPROCESS *Process;
  void *MappedSystemVa;
  void *StartVa;
  unsigned int ByteCount;
  unsigned int ByteOffset;
};

/* 292 */
struct VMBCHANNEL__
{
  int unused;
};

/* 169 */
const struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 347 */
struct __declspec(align(4)) _VSTOR_CHANNEL_ETW_TRACE_INFO
{
  _GUID ActivityId;
  unsigned int IOSize;
  unsigned __int8 IsRead;
  unsigned __int8 IsWrite;
};

/* 162 */
union $E9001894CD33E8DBC9EC27EA29B9AC82
{
  unsigned int InternalStatus;
  unsigned int QueueSortKey;
  unsigned int LinkTimeoutValue;
};

/* 161 */
struct _SCSI_REQUEST_BLOCK
{
  unsigned __int16 Length;
  unsigned __int8 Function;
  unsigned __int8 SrbStatus;
  unsigned __int8 ScsiStatus;
  unsigned __int8 PathId;
  unsigned __int8 TargetId;
  unsigned __int8 Lun;
  unsigned __int8 QueueTag;
  unsigned __int8 QueueAction;
  unsigned __int8 CdbLength;
  unsigned __int8 SenseInfoBufferLength;
  unsigned int SrbFlags;
  unsigned int DataTransferLength;
  unsigned int TimeOutValue;
  void *DataBuffer;
  void *SenseInfoBuffer;
  _SCSI_REQUEST_BLOCK *NextSrb;
  void *OriginalRequest;
  void *SrbExtension;
  $E9001894CD33E8DBC9EC27EA29B9AC82 ___u19;
  unsigned __int8 Cdb[16];
};

/* 106 */
struct $08481D05807C14C022C64127DBCB0DC5
{
  unsigned __int8 Type;
  unsigned __int8 Signalling;
  unsigned __int8 Size;
  unsigned __int8 Reserved1;
};

/* 107 */
struct $BDD1DEEA9085FB2031C94E38C028AF9F
{
  unsigned __int8 TimerType;
  unsigned __int8 TimerControlFlags;
  unsigned __int8 Hand;
  unsigned __int8 TimerMiscFlags;
};

/* 108 */
struct $1A64267CB6701B751C40AA7938D55A2C
{
  unsigned __int8 Timer2Type;
  unsigned __int8 Absolute : 1;
  unsigned __int8 Wake : 1;
  unsigned __int8 EncodedTolerableDelay : 6;
  unsigned __int8 Timer2Reserved1;
  unsigned __int8 Index : 1;
  unsigned __int8 Processor : 5;
  unsigned __int8 Inserted : 1;
  unsigned __int8 Expired : 1;
};

/* 109 */
struct $DC5C26BDF4D684F12F3A5D4531D3B949
{
  unsigned __int8 QueueType;
  unsigned __int8 Timer2Flags;
  unsigned __int8 QueueSize;
  unsigned __int8 Timer2Reserved2;
};

/* 110 */
struct $82359CCE575330AAB08AF0894BC28AE0
{
  unsigned __int8 ThreadType;
  unsigned __int8 Timer2Inserted : 1;
  unsigned __int8 Timer2Expiring : 1;
  unsigned __int8 Timer2CancelPending : 1;
  unsigned __int8 Timer2SetPending : 1;
  unsigned __int8 Timer2Running : 1;
  unsigned __int8 Timer2Disabled : 1;
  unsigned __int8 Timer2ReservedFlags : 2;
  unsigned __int8 ThreadControlFlags;
  unsigned __int8 QueueReserved;
};

/* 111 */
struct $9300EC2846D44244344338BB8331DF4E
{
  unsigned __int8 MutantType;
  unsigned __int8 QueueControlFlags;
  unsigned __int8 CycleProfiling : 1;
  unsigned __int8 CounterProfiling : 1;
  unsigned __int8 GroupScheduling : 1;
  unsigned __int8 AffinitySet : 1;
  unsigned __int8 Tagged : 1;
  unsigned __int8 EnergyProfiling : 1;
  unsigned __int8 Instrumented : 1;
  unsigned __int8 ThreadReservedControlFlags : 1;
  unsigned __int8 DebugActive;
};

/* 112 */
struct $311232CAD4ECFA502922D62D223D90C0
{
  _BYTE gap0;
  unsigned __int8 Abandoned : 1;
  unsigned __int8 DisableIncrement : 1;
  unsigned __int8 QueueReservedControlFlags : 6;
  unsigned __int8 DpcActive;
  unsigned __int8 MutantReserved;
};

/* 113 */
struct $6287A180EBF0351F83293B36E60E22FF
{
  _BYTE gap0;
  unsigned __int8 ThreadReserved;
};

/* 114 */
struct $4B94A638C9572C40F7312179A2B431F6
{
  _BYTE gap0;
  unsigned __int8 MutantSize;
};

/* 115 */
union $C4D88AE4D0E7721C194C9C49DA5D31CD
{
  volatile int Lock;
  int LockNV;
  $08481D05807C14C022C64127DBCB0DC5 __s2;
  $BDD1DEEA9085FB2031C94E38C028AF9F __s3;
  $1A64267CB6701B751C40AA7938D55A2C __s4;
  $DC5C26BDF4D684F12F3A5D4531D3B949 __s5;
  $82359CCE575330AAB08AF0894BC28AE0 __s6;
  $9300EC2846D44244344338BB8331DF4E __s7;
  $311232CAD4ECFA502922D62D223D90C0 __s8;
  $6287A180EBF0351F83293B36E60E22FF __s9;
  $4B94A638C9572C40F7312179A2B431F6 __s10;
};

/* 100 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 116 */
struct _DISPATCHER_HEADER
{
  $C4D88AE4D0E7721C194C9C49DA5D31CD ___u0;
  int SignalState;
  _LIST_ENTRY WaitListHead;
};

/* 117 */
struct _KEVENT
{
  _DISPATCHER_HEADER Header;
};

/* 366 */
struct _VSC_SRB_EXTENSION
{
  _VSTOR_CHANNEL_REQUEST Request;
  _VSTOR_CHANNEL_ETW_TRACE_INFO EtwTraceInfo;
  unsigned __int8 VmbPacketBuffer[];
};

/* 298 */
struct _FAST_MUTEX
{
  int Count;
  void *Owner;
  unsigned int Contention;
  _KEVENT Event;
  unsigned int OldIrql;
};

/* 386 */
struct __declspec(align(4)) $D12F31E27A35107AF57ED3394A3011EA
{
  VMBCHANNEL__ *Channel;
  unsigned __int8 Active;
};

/* 387 */
struct __unaligned __declspec(align(4)) _STOR_CHANNEL_VMBCHANNEL_CONTEXT
{
  VMBCHANNEL__ *Channel;
  _FAST_MUTEX Lock;
  void *UserContext;
  _VMSTORAGE_CHANNEL_PROPERTIES Properties;
  unsigned __int16 ProtocolVersion;
  int (__stdcall *EventCallback)(VMBCHANNEL__ *, _VSTOR_PACKET *) __declspec(align(4));
  unsigned __int16 MaxPacketSize;
  unsigned __int16 MaxSrbLength;
  unsigned __int8 MaxSrbSenseDataLength;
  unsigned __int8 ScsiSenseDataDescriptorFormatSupported;
  __declspec(align(4)) _DEVICE_OBJECT *DeviceObject;
  unsigned __int16 RequestedSubChannelCount;
  __declspec(align(4)) unsigned int SubChannelAffinity;
  $D12F31E27A35107AF57ED3394A3011EA SubChannel[15];
  VMBCHANNEL__ *volatile *ActiveChannel;
  _STOR_CHANNEL_PROCESSOR_INFO *ProcessorInfo;
};

/* 129 */
struct __declspec(align(4)) _KDEVICE_QUEUE_ENTRY
{
  _LIST_ENTRY DeviceListEntry;
  unsigned int SortKey;
  unsigned __int8 Inserted;
};

/* 219 */
struct $2D0742CE98D03A04EB425507D510F19D
{
  _LIST_ENTRY DmaWaitEntry;
  unsigned int NumberOfChannels;
  unsigned __int32 SyncCallback : 1;
  unsigned __int32 DmaContext : 1;
  unsigned __int32 ZeroMapRegisters : 1;
  unsigned __int32 Reserved : 29;
};

/* 220 */
union $9C1C546F9B0FD874C85554D263AF5C67
{
  _KDEVICE_QUEUE_ENTRY WaitQueueEntry;
  $2D0742CE98D03A04EB425507D510F19D __s1;
};

/* 29 */
enum _IO_ALLOCATION_ACTION : __int32
{
  KeepObject = 0x1,
  DeallocateObject = 0x2,
  DeallocateObjectKeepRegisters = 0x3,
};

/* 221 */
struct _WAIT_CONTEXT_BLOCK
{
  $9C1C546F9B0FD874C85554D263AF5C67 ___u0;
  _IO_ALLOCATION_ACTION (__stdcall *DeviceRoutine)(_DEVICE_OBJECT *, _IRP *, void *, void *);
  void *DeviceContext;
  unsigned int NumberOfMapRegisters;
  void *DeviceObject;
  void *CurrentIrp;
  _KDPC *BufferChainingDpc;
};

/* 222 */
union $7E176B30D335F3D1995872C8B03376B0
{
  _LIST_ENTRY ListEntry;
  _WAIT_CONTEXT_BLOCK Wcb;
};

/* 223 */
struct __declspec(align(4)) _KDEVICE_QUEUE
{
  __int16 Type;
  __int16 Size;
  _LIST_ENTRY DeviceListHead;
  unsigned int Lock;
  unsigned __int8 Busy;
};

/* 217 */
struct $82623AFB470F8517B6D8F9E43441C7E1
{
  unsigned __int8 Type;
  unsigned __int8 Importance;
  volatile unsigned __int16 Number;
};

/* 218 */
union $8F9F821E7C6CCD08A439BBA63C928EC6
{
  unsigned int TargetInfoAsUlong;
  $82623AFB470F8517B6D8F9E43441C7E1 __s1;
};

/* 104 */
struct _SINGLE_LIST_ENTRY
{
  _SINGLE_LIST_ENTRY *Next;
};

/* 216 */
struct _KDPC
{
  $8F9F821E7C6CCD08A439BBA63C928EC6 ___u0;
  _SINGLE_LIST_ENTRY DpcListEntry;
  unsigned int ProcessorHistory;
  void (__stdcall *DeferredRoutine)(_KDPC *, void *, void *, void *);
  void *DeferredContext;
  void *SystemArgument1;
  void *SystemArgument2;
  void *DpcData;
};

/* 90 */
struct _DEVICE_OBJECT
{
  __int16 Type;
  unsigned __int16 Size;
  int ReferenceCount;
  _DRIVER_OBJECT *DriverObject;
  _DEVICE_OBJECT *NextDevice;
  _DEVICE_OBJECT *AttachedDevice;
  _IRP *CurrentIrp;
  struct _IO_TIMER *Timer;
  unsigned int Flags;
  unsigned int Characteristics;
  _VPB *Vpb;
  void *DeviceExtension;
  unsigned int DeviceType;
  char StackSize;
  $7E176B30D335F3D1995872C8B03376B0 Queue;
  unsigned int AlignmentRequirement;
  _KDEVICE_QUEUE DeviceQueue;
  _KDPC Dpc;
  unsigned int ActiveThreadCount;
  void *SecurityDescriptor;
  _KEVENT DeviceLock;
  unsigned __int16 SectorSize;
  unsigned __int16 Spare1;
  _DEVOBJ_EXTENSION *DeviceObjectExtension;
  void *Reserved;
};

/* 384 */
struct _STOR_CHANNEL_PROCESSOR_INFO
{
  unsigned __int16 ProcessorIndex;
  unsigned __int16 BestChannel;
  unsigned __int16 Distance;
};

/* 393 */
typedef unsigned __int16 wchar_t;

/* 92 */
struct _UNICODE_STRING
{
  unsigned __int16 Length;
  unsigned __int16 MaximumLength;
  wchar_t *Buffer;
};

/* 91 */
struct _DRIVER_OBJECT
{
  __int16 Type;
  __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  unsigned int Flags;
  void *DriverStart;
  unsigned int DriverSize;
  void *DriverSection;
  _DRIVER_EXTENSION *DriverExtension;
  _UNICODE_STRING DriverName;
  _UNICODE_STRING *HardwareDatabase;
  _FAST_IO_DISPATCH *FastIoDispatch;
  int (__stdcall *DriverInit)(_DRIVER_OBJECT *, _UNICODE_STRING *);
  void (__stdcall *DriverStartIo)(_DEVICE_OBJECT *, _IRP *);
  void (__stdcall *DriverUnload)(_DRIVER_OBJECT *);
  int (__stdcall *MajorFunction[28])(_DEVICE_OBJECT *, _IRP *);
};

/* 125 */
union $A27DC56A689DD4F447A7DF03D6E3A259
{
  _IRP *MasterIrp;
  int IrpCount;
  void *SystemBuffer;
};

/* 95 */
union $250F5FE22B4503EFD7D48C86CC7F2167
{
  int Status;
  void *Pointer;
};

/* 96 */
struct _IO_STATUS_BLOCK
{
  $250F5FE22B4503EFD7D48C86CC7F2167 ___u0;
  unsigned int Information;
};

/* 126 */
union $282655BB7CE4A0ECF0847F8EE5278D9D
{
  void (__stdcall *UserApcRoutine)(void *, _IO_STATUS_BLOCK *, unsigned int);
  void *IssuingProcess;
};

/* 127 */
struct $A28E547B69A77EEC84BC18284AAF64D7
{
  $282655BB7CE4A0ECF0847F8EE5278D9D ___u0;
  void *UserApcContext;
};

/* 72 */
struct $FAF74743FBE1C8632047CFB668F7028A
{
  unsigned int LowPart;
  int HighPart;
};

/* 73 */
union _LARGE_INTEGER
{
  $FAF74743FBE1C8632047CFB668F7028A __s0;
  $FAF74743FBE1C8632047CFB668F7028A u;
  __int64 QuadPart;
};

/* 128 */
union $E07977D62BEDFCBF453B60D90C197A5C
{
  $A28E547B69A77EEC84BC18284AAF64D7 AsynchronousParameters;
  _LARGE_INTEGER AllocationSize;
};

/* 210 */
union $3C5970A3A0B9FEE882D8B371A394CE45
{
  _KDEVICE_QUEUE_ENTRY DeviceQueueEntry;
  void *DriverContext[4];
};

/* 211 */
union $8F9DB242FE7A2F6762C09958C8FEC2F7
{
  _IO_STACK_LOCATION *CurrentStackLocation;
  unsigned int PacketType;
};

/* 212 */
struct $7969F106BCFFC9446FCC50F6E86C56C2
{
  $3C5970A3A0B9FEE882D8B371A394CE45 ___u0;
  struct _KTHREAD *Thread;
  char *AuxiliaryBuffer;
  _LIST_ENTRY ListEntry;
  $8F9DB242FE7A2F6762C09958C8FEC2F7 ___u4;
  _FILE_OBJECT *OriginalFileObject;
};

/* 213 */
struct __declspec(align(2)) _KAPC
{
  unsigned __int8 Type;
  unsigned __int8 SpareByte0;
  unsigned __int8 Size;
  unsigned __int8 SpareByte1;
  unsigned int SpareLong0;
  struct _KTHREAD *Thread;
  _LIST_ENTRY ApcListEntry;
  void *Reserved[3];
  void *NormalContext;
  void *SystemArgument1;
  void *SystemArgument2;
  char ApcStateIndex;
  char ApcMode;
  unsigned __int8 Inserted;
};

/* 214 */
union $AEDFFB425936D0D636474A919EF2223F
{
  $7969F106BCFFC9446FCC50F6E86C56C2 Overlay;
  _KAPC Apc;
  void *CompletionKey;
};

/* 124 */
struct _IRP
{
  __int16 Type;
  unsigned __int16 Size;
  _MDL *MdlAddress;
  unsigned int Flags;
  $A27DC56A689DD4F447A7DF03D6E3A259 AssociatedIrp;
  _LIST_ENTRY ThreadListEntry;
  _IO_STATUS_BLOCK IoStatus;
  char RequestorMode;
  unsigned __int8 PendingReturned;
  char StackCount;
  char CurrentLocation;
  unsigned __int8 Cancel;
  unsigned __int8 CancelIrql;
  char ApcEnvironment;
  unsigned __int8 AllocationFlags;
  _IO_STATUS_BLOCK *UserIosb;
  _KEVENT *UserEvent;
  $E07977D62BEDFCBF453B60D90C197A5C Overlay;
  void (__stdcall *CancelRoutine)(_DEVICE_OBJECT *, _IRP *);
  void *UserBuffer;
  $AEDFFB425936D0D636474A919EF2223F Tail;
};

/* 159 */
struct _VPB
{
  __int16 Type;
  __int16 Size;
  unsigned __int16 Flags;
  unsigned __int16 VolumeLabelLength;
  _DEVICE_OBJECT *DeviceObject;
  _DEVICE_OBJECT *RealDevice;
  unsigned int SerialNumber;
  unsigned int ReferenceCount;
  wchar_t VolumeLabel[32];
};

/* 224 */
struct _DEVOBJ_EXTENSION
{
  __int16 Type;
  unsigned __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  unsigned int PowerFlags;
  struct _DEVICE_OBJECT_POWER_EXTENSION *Dope;
  unsigned int ExtensionFlags;
  void *DeviceNode;
  _DEVICE_OBJECT *AttachedTo;
  int StartIoCount;
  int StartIoKey;
  unsigned int StartIoFlags;
  _VPB *Vpb;
  void *DependencyNode;
  void *InterruptContext;
  void *VerifierContext;
};

/* 93 */
struct _DRIVER_EXTENSION
{
  _DRIVER_OBJECT *DriverObject;
  int (__stdcall *AddDevice)(_DRIVER_OBJECT *, _DEVICE_OBJECT *);
  unsigned int Count;
  _UNICODE_STRING ServiceKeyName;
};

/* 215 */
struct _FAST_IO_DISPATCH
{
  unsigned int SizeOfFastIoDispatch;
  unsigned __int8 (__stdcall *FastIoCheckIfPossible)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, unsigned __int8, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoRead)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, void *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned __int8, unsigned int, void *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryBasicInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_BASIC_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryStandardInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_STANDARD_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoLock)(_FILE_OBJECT *, _LARGE_INTEGER *, _LARGE_INTEGER *, struct _KPROCESS *, unsigned int, unsigned __int8, unsigned __int8, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockSingle)(_FILE_OBJECT *, _LARGE_INTEGER *, _LARGE_INTEGER *, struct _KPROCESS *, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockAll)(_FILE_OBJECT *, struct _KPROCESS *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoUnlockAllByKey)(_FILE_OBJECT *, void *, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoDeviceControl)(_FILE_OBJECT *, unsigned __int8, void *, unsigned int, void *, unsigned int, unsigned int, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  void (__stdcall *AcquireFileForNtCreateSection)(_FILE_OBJECT *);
  void (__stdcall *ReleaseFileForNtCreateSection)(_FILE_OBJECT *);
  void (__stdcall *FastIoDetachDevice)(_DEVICE_OBJECT *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryNetworkOpenInfo)(_FILE_OBJECT *, unsigned __int8, _FILE_NETWORK_OPEN_INFORMATION *, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  int (__stdcall *AcquireForModWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, _ERESOURCE **, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlRead)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, _MDL **, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlReadComplete)(_FILE_OBJECT *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *PrepareMdlWrite)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, _MDL **, _IO_STATUS_BLOCK *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlWriteComplete)(_FILE_OBJECT *, _LARGE_INTEGER *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoReadCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, void *, _MDL **, _IO_STATUS_BLOCK *, _COMPRESSED_DATA_INFO *, unsigned int, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoWriteCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, unsigned int, unsigned int, void *, _MDL **, _IO_STATUS_BLOCK *, _COMPRESSED_DATA_INFO *, unsigned int, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlReadCompleteCompressed)(_FILE_OBJECT *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *MdlWriteCompleteCompressed)(_FILE_OBJECT *, _LARGE_INTEGER *, _MDL *, _DEVICE_OBJECT *);
  unsigned __int8 (__stdcall *FastIoQueryOpen)(_IRP *, _FILE_NETWORK_OPEN_INFORMATION *, _DEVICE_OBJECT *);
  int (__stdcall *ReleaseForModWrite)(_FILE_OBJECT *, _ERESOURCE *, _DEVICE_OBJECT *);
  int (__stdcall *AcquireForCcFlush)(_FILE_OBJECT *, _DEVICE_OBJECT *);
  int (__stdcall *ReleaseForCcFlush)(_FILE_OBJECT *, _DEVICE_OBJECT *);
};

/* 139 */
struct $EA486013CB454A1E86B6078F7660F1A1
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 FileAttributes;
  unsigned __int16 ShareAccess;
  unsigned int EaLength;
};

/* 141 */
struct $40CDC29D2FE4597547D8D207C40218DF
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 Reserved;
  unsigned __int16 ShareAccess;
  _NAMED_PIPE_CREATE_PARAMETERS *Parameters;
};

/* 143 */
struct $77E746FF7C63BE6D5C1C6122D28362FD
{
  _IO_SECURITY_CONTEXT *SecurityContext;
  unsigned int Options;
  unsigned __int16 Reserved;
  unsigned __int16 ShareAccess;
  _MAILSLOT_CREATE_PARAMETERS *Parameters;
};

/* 144 */
struct $9720A69557804ADE75CB029AF8FE7917
{
  unsigned int Length;
  unsigned int Key;
  _LARGE_INTEGER ByteOffset;
};

/* 30 */
enum _FILE_INFORMATION_CLASS : __int32
{
  FileDirectoryInformation = 0x1,
  FileFullDirectoryInformation = 0x2,
  FileBothDirectoryInformation = 0x3,
  FileBasicInformation = 0x4,
  FileStandardInformation = 0x5,
  FileInternalInformation = 0x6,
  FileEaInformation = 0x7,
  FileAccessInformation = 0x8,
  FileNameInformation = 0x9,
  FileRenameInformation = 0xA,
  FileLinkInformation = 0xB,
  FileNamesInformation = 0xC,
  FileDispositionInformation = 0xD,
  FilePositionInformation = 0xE,
  FileFullEaInformation = 0xF,
  FileModeInformation = 0x10,
  FileAlignmentInformation = 0x11,
  FileAllInformation = 0x12,
  FileAllocationInformation = 0x13,
  FileEndOfFileInformation = 0x14,
  FileAlternateNameInformation = 0x15,
  FileStreamInformation = 0x16,
  FilePipeInformation = 0x17,
  FilePipeLocalInformation = 0x18,
  FilePipeRemoteInformation = 0x19,
  FileMailslotQueryInformation = 0x1A,
  FileMailslotSetInformation = 0x1B,
  FileCompressionInformation = 0x1C,
  FileObjectIdInformation = 0x1D,
  FileCompletionInformation = 0x1E,
  FileMoveClusterInformation = 0x1F,
  FileQuotaInformation = 0x20,
  FileReparsePointInformation = 0x21,
  FileNetworkOpenInformation = 0x22,
  FileAttributeTagInformation = 0x23,
  FileTrackingInformation = 0x24,
  FileIdBothDirectoryInformation = 0x25,
  FileIdFullDirectoryInformation = 0x26,
  FileValidDataLengthInformation = 0x27,
  FileShortNameInformation = 0x28,
  FileIoCompletionNotificationInformation = 0x29,
  FileIoStatusBlockRangeInformation = 0x2A,
  FileIoPriorityHintInformation = 0x2B,
  FileSfioReserveInformation = 0x2C,
  FileSfioVolumeInformation = 0x2D,
  FileHardLinkInformation = 0x2E,
  FileProcessIdsUsingFileInformation = 0x2F,
  FileNormalizedNameInformation = 0x30,
  FileNetworkPhysicalNameInformation = 0x31,
  FileIdGlobalTxDirectoryInformation = 0x32,
  FileIsRemoteDeviceInformation = 0x33,
  FileUnusedInformation = 0x34,
  FileNumaNodeInformation = 0x35,
  FileStandardLinkInformation = 0x36,
  FileRemoteProtocolInformation = 0x37,
  FileRenameInformationBypassAccessCheck = 0x38,
  FileLinkInformationBypassAccessCheck = 0x39,
  FileVolumeNameInformation = 0x3A,
  FileIdInformation = 0x3B,
  FileIdExtdDirectoryInformation = 0x3C,
  FileReplaceCompletionInformation = 0x3D,
  FileHardLinkFullIdInformation = 0x3E,
  FileIdExtdBothDirectoryInformation = 0x3F,
  FileMaximumInformation = 0x40,
};

/* 145 */
struct $6F0BC168E1594653C4143BBCBABBCCD6
{
  unsigned int Length;
  _UNICODE_STRING *FileName;
  _FILE_INFORMATION_CLASS FileInformationClass;
  unsigned int FileIndex;
};

/* 146 */
struct $50A7D1BFBD4B9BBEBCBBE3D92FEB6A61
{
  unsigned int Length;
  unsigned int CompletionFilter;
};

/* 147 */
struct $06636AAA92A83BD58388E023ACF60F18
{
  unsigned int Length;
  _FILE_INFORMATION_CLASS FileInformationClass;
};

/* 148 */
struct $BBD6C80A82148A7CAD5B218A5A41C1D9
{
  unsigned __int8 ReplaceIfExists;
  unsigned __int8 AdvanceOnly;
};

/* 149 */
union $88FBC804D5489C4AA8CD7F5700EC3258
{
  $BBD6C80A82148A7CAD5B218A5A41C1D9 __s0;
  unsigned int ClusterCount;
  void *DeleteHandle;
};

/* 150 */
struct $8D831D3AB31BDE5A184AC2BC7C5DF6A4
{
  unsigned int Length;
  _FILE_INFORMATION_CLASS FileInformationClass;
  _FILE_OBJECT *FileObject;
  $88FBC804D5489C4AA8CD7F5700EC3258 ___u3;
};

/* 151 */
struct $43049A1C9CD1076EE2F76BA56B9556D6
{
  unsigned int Length;
  void *EaList;
  unsigned int EaListLength;
  unsigned int EaIndex;
};

/* 152 */
struct $44CAF4394294FD1AA9144BF9A47D2B76
{
  unsigned int Length;
};

/* 31 */
enum _FSINFOCLASS : __int32
{
  FileFsVolumeInformation = 0x1,
  FileFsLabelInformation = 0x2,
  FileFsSizeInformation = 0x3,
  FileFsDeviceInformation = 0x4,
  FileFsAttributeInformation = 0x5,
  FileFsControlInformation = 0x6,
  FileFsFullSizeInformation = 0x7,
  FileFsObjectIdInformation = 0x8,
  FileFsDriverPathInformation = 0x9,
  FileFsVolumeFlagsInformation = 0xA,
  FileFsSectorSizeInformation = 0xB,
  FileFsDataCopyInformation = 0xC,
  FileFsMetadataSizeInformation = 0xD,
  FileFsMaximumInformation = 0xE,
};

/* 153 */
struct $A8645AF0B8014D8E47C9A317215636E1
{
  unsigned int Length;
  _FSINFOCLASS FsInformationClass;
};

/* 154 */
struct $1452ECD7C6E5AB3C058EED8909EEC64B
{
  unsigned int OutputBufferLength;
  unsigned int InputBufferLength;
  unsigned int FsControlCode;
  void *Type3InputBuffer;
};

/* 155 */
struct $02C42C2BB964BFB60FF4BB2C0EA9092D
{
  _LARGE_INTEGER *Length;
  unsigned int Key;
  _LARGE_INTEGER ByteOffset;
};

/* 156 */
struct $343716E60DEC8CEA3C236115305CA9A5
{
  unsigned int OutputBufferLength;
  unsigned int InputBufferLength;
  unsigned int IoControlCode;
  void *Type3InputBuffer;
};

/* 157 */
struct $79FAFD50642EF9FCAC6F48CCDD5826D7
{
  unsigned int SecurityInformation;
  unsigned int Length;
};

/* 158 */
struct $29E784017BF8D630C3CED492840B3F1E
{
  unsigned int SecurityInformation;
  void *SecurityDescriptor;
};

/* 160 */
struct $43EA69A59FC723A53188D645A482212C
{
  _VPB *Vpb;
  _DEVICE_OBJECT *DeviceObject;
};

/* 163 */
struct $9D2890F1086664EAE9278060BF7B4E5F
{
  _SCSI_REQUEST_BLOCK *Srb;
};

/* 167 */
struct $64CBEEFADAA38AAD69D06C1708C5E9B7
{
  unsigned int Length;
  void *StartSid;
  _FILE_GET_QUOTA_INFORMATION *SidList;
  unsigned int SidListLength;
};

/* 32 */
enum _DEVICE_RELATION_TYPE : __int32
{
  BusRelations = 0x0,
  EjectionRelations = 0x1,
  PowerRelations = 0x2,
  RemovalRelations = 0x3,
  TargetDeviceRelation = 0x4,
  SingleBusRelations = 0x5,
  TransportRelations = 0x6,
};

/* 168 */
struct $50574F1517873E1A51045E216E10A94B
{
  _DEVICE_RELATION_TYPE Type;
};

/* 171 */
struct $E7CDFB3CD6DAEA23F0494C2031BC450C
{
  const _GUID *InterfaceType;
  unsigned __int16 Size;
  unsigned __int16 Version;
  _INTERFACE *Interface;
  void *InterfaceSpecificData;
};

/* 173 */
struct $A9429BCD6E091FF8FF2F781E929E6234
{
  _DEVICE_CAPABILITIES *Capabilities;
};

/* 187 */
struct $1478A889361DA355AA49AA8255E12147
{
  _IO_RESOURCE_REQUIREMENTS_LIST *IoResourceRequirementList;
};

/* 188 */
struct $5E4425892CB91929A7D567B5DA0A3F92
{
  unsigned int WhichSpace;
  void *Buffer;
  unsigned int Offset;
  unsigned int Length;
};

/* 189 */
struct $B367FCCFB95D7087158A479FE9C2D0D7
{
  unsigned __int8 Lock;
};

/* 33 */
enum BUS_QUERY_ID_TYPE : __int32
{
  BusQueryDeviceID = 0x0,
  BusQueryHardwareIDs = 0x1,
  BusQueryCompatibleIDs = 0x2,
  BusQueryInstanceID = 0x3,
  BusQueryDeviceSerialNumber = 0x4,
  BusQueryContainerID = 0x5,
};

/* 190 */
struct $3D8AE520A88A57A2589DCB32DE619AA0
{
  BUS_QUERY_ID_TYPE IdType;
};

/* 34 */
enum DEVICE_TEXT_TYPE : __int32
{
  DeviceTextDescription = 0x0,
  DeviceTextLocationInformation = 0x1,
};

/* 191 */
struct $DF4B2A721E46850DFBF98C841644920F
{
  DEVICE_TEXT_TYPE DeviceTextType;
  unsigned int LocaleId;
};

/* 35 */
enum _DEVICE_USAGE_NOTIFICATION_TYPE : __int32
{
  DeviceUsageTypeUndefined = 0x0,
  DeviceUsageTypePaging = 0x1,
  DeviceUsageTypeHibernation = 0x2,
  DeviceUsageTypeDumpFile = 0x3,
  DeviceUsageTypeBoot = 0x4,
  DeviceUsageTypePostDisplay = 0x5,
};

/* 192 */
struct $43382A7C461080833D43E1898249B591
{
  unsigned __int8 InPath;
  unsigned __int8 Reserved[3];
  _DEVICE_USAGE_NOTIFICATION_TYPE Type;
};

/* 36 */
enum _SYSTEM_POWER_STATE : __int32
{
  PowerSystemUnspecified = 0x0,
  PowerSystemWorking = 0x1,
  PowerSystemSleeping1 = 0x2,
  PowerSystemSleeping2 = 0x3,
  PowerSystemSleeping3 = 0x4,
  PowerSystemHibernate = 0x5,
  PowerSystemShutdown = 0x6,
  PowerSystemMaximum = 0x7,
};

/* 193 */
struct $D3FB6843FF15A25B8CE7A328170C1D4A
{
  _SYSTEM_POWER_STATE PowerState;
};

/* 195 */
struct $EBB514EFE5E0F51C545802D7971964F4
{
  _POWER_SEQUENCE *PowerSequence;
};

/* 196 */
struct $76514DB155979F88E47E6F460A9859AB
{
  unsigned __int32 Reserved1 : 8;
  unsigned __int32 TargetSystemState : 4;
  unsigned __int32 EffectiveSystemState : 4;
  unsigned __int32 CurrentSystemState : 4;
  unsigned __int32 IgnoreHibernationPath : 1;
  unsigned __int32 PseudoTransition : 1;
  unsigned __int32 Reserved2 : 10;
};

/* 197 */
union $C13D918EFEC47F6D15730144A9E26EC9
{
  $76514DB155979F88E47E6F460A9859AB __s0;
  unsigned int ContextAsUlong;
};

/* 198 */
struct _SYSTEM_POWER_STATE_CONTEXT
{
  $C13D918EFEC47F6D15730144A9E26EC9 ___u0;
};

/* 200 */
union $2ACB8A2A4EA7B9CF58409B8FA229C65F
{
  unsigned int SystemContext;
  _SYSTEM_POWER_STATE_CONTEXT SystemPowerStateContext;
};

/* 37 */
enum _POWER_STATE_TYPE : __int32
{
  SystemPowerState = 0x0,
  DevicePowerState = 0x1,
};

/* 6 */
enum _DEVICE_POWER_STATE : __int32
{
  PowerDeviceUnspecified = 0x0,
  PowerDeviceD0 = 0x1,
  PowerDeviceD1 = 0x2,
  PowerDeviceD2 = 0x3,
  PowerDeviceD3 = 0x4,
  PowerDeviceMaximum = 0x5,
};

/* 199 */
union _POWER_STATE
{
  _SYSTEM_POWER_STATE SystemState;
  _DEVICE_POWER_STATE DeviceState;
};

/* 38 */
enum POWER_ACTION : __int32
{
  PowerActionNone = 0x0,
  PowerActionReserved = 0x1,
  PowerActionSleep = 0x2,
  PowerActionHibernate = 0x3,
  PowerActionShutdown = 0x4,
  PowerActionShutdownReset = 0x5,
  PowerActionShutdownOff = 0x6,
  PowerActionWarmEject = 0x7,
  PowerActionDisplayOff = 0x8,
};

/* 201 */
struct $95A9CEEA8BB4D0E71F3464AA0C3D98B5
{
  $2ACB8A2A4EA7B9CF58409B8FA229C65F ___u0;
  _POWER_STATE_TYPE Type;
  _POWER_STATE State;
  POWER_ACTION ShutdownType;
};

/* 205 */
struct $C57AD7B7B1055D6F8670B204B9684330
{
  _CM_RESOURCE_LIST *AllocatedResources;
  _CM_RESOURCE_LIST *AllocatedResourcesTranslated;
};

/* 206 */
struct $27D1A893733DBE62F2FCC36974CB79FA
{
  unsigned int ProviderId;
  void *DataPath;
  unsigned int BufferSize;
  void *Buffer;
};

/* 207 */
struct $228F32E73A128818A25FF1959272C294
{
  void *Argument1;
  void *Argument2;
  void *Argument3;
  void *Argument4;
};

/* 208 */
union $4D706E835128CD06A9BD4653FEA8C5CD
{
  $EA486013CB454A1E86B6078F7660F1A1 Create;
  $40CDC29D2FE4597547D8D207C40218DF CreatePipe;
  $77E746FF7C63BE6D5C1C6122D28362FD CreateMailslot;
  $9720A69557804ADE75CB029AF8FE7917 Read;
  $9720A69557804ADE75CB029AF8FE7917 Write;
  $6F0BC168E1594653C4143BBCBABBCCD6 QueryDirectory;
  $50A7D1BFBD4B9BBEBCBBE3D92FEB6A61 NotifyDirectory;
  $06636AAA92A83BD58388E023ACF60F18 QueryFile;
  $8D831D3AB31BDE5A184AC2BC7C5DF6A4 SetFile;
  $43049A1C9CD1076EE2F76BA56B9556D6 QueryEa;
  $44CAF4394294FD1AA9144BF9A47D2B76 SetEa;
  $A8645AF0B8014D8E47C9A317215636E1 QueryVolume;
  $A8645AF0B8014D8E47C9A317215636E1 SetVolume;
  $1452ECD7C6E5AB3C058EED8909EEC64B FileSystemControl;
  $02C42C2BB964BFB60FF4BB2C0EA9092D LockControl;
  $343716E60DEC8CEA3C236115305CA9A5 DeviceIoControl;
  $79FAFD50642EF9FCAC6F48CCDD5826D7 QuerySecurity;
  $29E784017BF8D630C3CED492840B3F1E SetSecurity;
  $43EA69A59FC723A53188D645A482212C MountVolume;
  $43EA69A59FC723A53188D645A482212C VerifyVolume;
  $9D2890F1086664EAE9278060BF7B4E5F Scsi;
  $64CBEEFADAA38AAD69D06C1708C5E9B7 QueryQuota;
  $44CAF4394294FD1AA9144BF9A47D2B76 SetQuota;
  $50574F1517873E1A51045E216E10A94B QueryDeviceRelations;
  $E7CDFB3CD6DAEA23F0494C2031BC450C QueryInterface;
  $A9429BCD6E091FF8FF2F781E929E6234 DeviceCapabilities;
  $1478A889361DA355AA49AA8255E12147 FilterResourceRequirements;
  $5E4425892CB91929A7D567B5DA0A3F92 ReadWriteConfig;
  $B367FCCFB95D7087158A479FE9C2D0D7 SetLock;
  $3D8AE520A88A57A2589DCB32DE619AA0 QueryId;
  $DF4B2A721E46850DFBF98C841644920F QueryDeviceText;
  $43382A7C461080833D43E1898249B591 UsageNotification;
  $D3FB6843FF15A25B8CE7A328170C1D4A WaitWake;
  $EBB514EFE5E0F51C545802D7971964F4 PowerSequence;
  $95A9CEEA8BB4D0E71F3464AA0C3D98B5 Power;
  $C57AD7B7B1055D6F8670B204B9684330 StartDevice;
  $27D1A893733DBE62F2FCC36974CB79FA WMI;
  $228F32E73A128818A25FF1959272C294 Others;
};

/* 209 */
struct __unaligned __declspec(align(4)) _IO_STACK_LOCATION
{
  unsigned __int8 MajorFunction;
  unsigned __int8 MinorFunction;
  unsigned __int8 Flags;
  unsigned __int8 Control;
  $4D706E835128CD06A9BD4653FEA8C5CD Parameters;
  _DEVICE_OBJECT *DeviceObject;
  _FILE_OBJECT *FileObject;
  int (__stdcall *CompletionRoutine)(_DEVICE_OBJECT *, _IRP *, void *);
  void *Context;
};

/* 94 */
struct _FILE_OBJECT
{
  __int16 Type;
  __int16 Size;
  _DEVICE_OBJECT *DeviceObject;
  _VPB *Vpb;
  void *FsContext;
  void *FsContext2;
  _SECTION_OBJECT_POINTERS *SectionObjectPointer;
  void *PrivateCacheMap;
  int FinalStatus;
  _FILE_OBJECT *RelatedFileObject;
  unsigned __int8 LockOperation;
  unsigned __int8 DeletePending;
  unsigned __int8 ReadAccess;
  unsigned __int8 WriteAccess;
  unsigned __int8 DeleteAccess;
  unsigned __int8 SharedRead;
  unsigned __int8 SharedWrite;
  unsigned __int8 SharedDelete;
  unsigned int Flags;
  _UNICODE_STRING FileName;
  _LARGE_INTEGER CurrentByteOffset;
  unsigned int Waiters;
  unsigned int Busy;
  void *LastLock;
  _KEVENT Lock;
  _KEVENT Event;
  _IO_COMPLETION_CONTEXT *CompletionContext;
  unsigned int IrpListLock;
  _LIST_ENTRY IrpList;
  void *FileObjectExtension;
};

/* 97 */
struct __declspec(align(8)) _FILE_BASIC_INFORMATION
{
  _LARGE_INTEGER CreationTime;
  _LARGE_INTEGER LastAccessTime;
  _LARGE_INTEGER LastWriteTime;
  _LARGE_INTEGER ChangeTime;
  unsigned int FileAttributes;
};

/* 98 */
struct __declspec(align(4)) _FILE_STANDARD_INFORMATION
{
  _LARGE_INTEGER AllocationSize;
  _LARGE_INTEGER EndOfFile;
  unsigned int NumberOfLinks;
  unsigned __int8 DeletePending;
  unsigned __int8 Directory;
};

/* 99 */
struct __declspec(align(8)) _FILE_NETWORK_OPEN_INFORMATION
{
  _LARGE_INTEGER CreationTime;
  _LARGE_INTEGER LastAccessTime;
  _LARGE_INTEGER LastWriteTime;
  _LARGE_INTEGER ChangeTime;
  _LARGE_INTEGER AllocationSize;
  _LARGE_INTEGER EndOfFile;
  unsigned int FileAttributes;
};

/* 118 */
struct $9959C6898638794B7A02F04E7F980F81
{
  unsigned __int8 ReservedLowFlags;
  unsigned __int8 WaiterPriority;
};

/* 119 */
union $790FC4C467C7CF3807E462E714099B7E
{
  unsigned __int16 Flag;
  $9959C6898638794B7A02F04E7F980F81 __s1;
};

/* 105 */
struct _KWAIT_CHAIN
{
  _SINGLE_LIST_ENTRY Head;
};

/* 101 */
struct $E71B718CD8428E7C8AA4A0868051E710
{
  unsigned __int32 IoPriorityBoosted : 1;
  unsigned __int32 OwnerReferenced : 1;
  unsigned __int32 IoQoSPriorityBoosted : 1;
  unsigned __int32 OwnerCount : 29;
};

/* 102 */
union $1D3C19C6A57281A9262FD2634784B6D7
{
  $E71B718CD8428E7C8AA4A0868051E710 __s0;
  unsigned int TableSize;
};

/* 103 */
struct _OWNER_ENTRY
{
  unsigned int OwnerThread;
  $1D3C19C6A57281A9262FD2634784B6D7 ___u1;
};

/* 120 */
union $B8D4EB9E6E3D1A926634FE9A5064A2BB
{
  void *Address;
  unsigned int CreatorBackTraceIndex;
};

/* 121 */
struct _ERESOURCE
{
  _LIST_ENTRY SystemResourcesList;
  _OWNER_ENTRY *OwnerTable;
  __int16 ActiveCount;
  $790FC4C467C7CF3807E462E714099B7E ___u3;
  _KWAIT_CHAIN SharedWaiters;
  _KEVENT *ExclusiveWaiters;
  _OWNER_ENTRY OwnerEntry;
  unsigned int ActiveEntries;
  unsigned int ContentionCount;
  unsigned int NumberOfSharedWaiters;
  unsigned int NumberOfExclusiveWaiters;
  $B8D4EB9E6E3D1A926634FE9A5064A2BB ___u11;
  unsigned int SpinLock;
};

/* 123 */
struct _COMPRESSED_DATA_INFO
{
  unsigned __int16 CompressionFormatAndEngine;
  unsigned __int8 CompressionUnitShift;
  unsigned __int8 ChunkShift;
  unsigned __int8 ClusterShift;
  unsigned __int8 Reserved;
  unsigned __int16 NumberOfChunks;
  unsigned int CompressedChunkSizes[1];
};

/* 138 */
struct _IO_SECURITY_CONTEXT
{
  _SECURITY_QUALITY_OF_SERVICE *SecurityQos;
  _ACCESS_STATE *AccessState;
  unsigned int DesiredAccess;
  unsigned int FullCreateOptions;
};

/* 140 */
struct __declspec(align(8)) _NAMED_PIPE_CREATE_PARAMETERS
{
  unsigned int NamedPipeType;
  unsigned int ReadMode;
  unsigned int CompletionMode;
  unsigned int MaximumInstances;
  unsigned int InboundQuota;
  unsigned int OutboundQuota;
  _LARGE_INTEGER DefaultTimeout;
  unsigned __int8 TimeoutSpecified;
};

/* 142 */
struct __declspec(align(8)) _MAILSLOT_CREATE_PARAMETERS
{
  unsigned int MailslotQuota;
  unsigned int MaximumMessageSize;
  _LARGE_INTEGER ReadTimeout;
  unsigned __int8 TimeoutSpecified;
};

/* 164 */
struct _SID_IDENTIFIER_AUTHORITY
{
  unsigned __int8 Value[6];
};

/* 165 */
struct _SID
{
  unsigned __int8 Revision;
  unsigned __int8 SubAuthorityCount;
  _SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
  unsigned int SubAuthority[1];
};

/* 166 */
struct _FILE_GET_QUOTA_INFORMATION
{
  unsigned int NextEntryOffset;
  unsigned int SidLength;
  _SID Sid;
};

/* 170 */
struct _INTERFACE
{
  unsigned __int16 Size;
  unsigned __int16 Version;
  void *Context;
  void (__stdcall *InterfaceReference)(void *);
  void (__stdcall *InterfaceDereference)(void *);
};

/* 172 */
struct _DEVICE_CAPABILITIES
{
  unsigned __int16 Size;
  unsigned __int16 Version;
  unsigned __int32 DeviceD1 : 1;
  unsigned __int32 DeviceD2 : 1;
  unsigned __int32 LockSupported : 1;
  unsigned __int32 EjectSupported : 1;
  unsigned __int32 Removable : 1;
  unsigned __int32 DockDevice : 1;
  unsigned __int32 UniqueID : 1;
  unsigned __int32 SilentInstall : 1;
  unsigned __int32 RawDeviceOK : 1;
  unsigned __int32 SurpriseRemovalOK : 1;
  unsigned __int32 WakeFromD0 : 1;
  unsigned __int32 WakeFromD1 : 1;
  unsigned __int32 WakeFromD2 : 1;
  unsigned __int32 WakeFromD3 : 1;
  unsigned __int32 HardwareDisabled : 1;
  unsigned __int32 NonDynamic : 1;
  unsigned __int32 WarmEjectSupported : 1;
  unsigned __int32 NoDisplayInUI : 1;
  unsigned __int32 Reserved1 : 1;
  unsigned __int32 WakeFromInterrupt : 1;
  unsigned __int32 Reserved : 12;
  unsigned int Address;
  unsigned int UINumber;
  _DEVICE_POWER_STATE DeviceState[7];
  _SYSTEM_POWER_STATE SystemWake;
  _DEVICE_POWER_STATE DeviceWake;
  unsigned int D1Latency;
  unsigned int D2Latency;
  unsigned int D3Latency;
};

/* 28 */
enum _INTERFACE_TYPE : __int32
{
  InterfaceTypeUndefined = 0xFFFFFFFF,
  Internal = 0x0,
  Isa = 0x1,
  Eisa = 0x2,
  MicroChannel = 0x3,
  TurboChannel = 0x4,
  PCIBus = 0x5,
  VMEBus = 0x6,
  NuBus = 0x7,
  PCMCIABus = 0x8,
  CBus = 0x9,
  MPIBus = 0xA,
  MPSABus = 0xB,
  ProcessorInternal = 0xC,
  InternalPowerBus = 0xD,
  PNPISABus = 0xE,
  PNPBus = 0xF,
  Vmcs = 0x10,
  ACPIBus = 0x11,
  MaximumInterfaceType = 0x12,
};

/* 174 */
struct $A46720D08D4953A701BC2CEF123A3A5E
{
  unsigned int Length;
  unsigned int Alignment;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 26 */
enum _IRQ_DEVICE_POLICY : __int32
{
  IrqPolicyMachineDefault = 0x0,
  IrqPolicyAllCloseProcessors = 0x1,
  IrqPolicyOneCloseProcessor = 0x2,
  IrqPolicyAllProcessorsInMachine = 0x3,
  IrqPolicySpecifiedProcessors = 0x4,
  IrqPolicySpreadMessagesAcrossAllProcessors = 0x5,
  IrqPolicyAllProcessorsInMachineWhenSteered = 0x6,
};

/* 27 */
enum _IRQ_PRIORITY : __int32
{
  IrqPriorityUndefined = 0x0,
  IrqPriorityLow = 0x1,
  IrqPriorityNormal = 0x2,
  IrqPriorityHigh = 0x3,
};

/* 175 */
struct $C47234A5E135268FB8DC1B2B94727F34
{
  unsigned int MinimumVector;
  unsigned int MaximumVector;
  _IRQ_DEVICE_POLICY AffinityPolicy;
  _IRQ_PRIORITY PriorityPolicy;
  unsigned int TargetedProcessors;
};

/* 176 */
struct $290D34FD7868E94AFEC0383C08CB9B28
{
  unsigned int MinimumChannel;
  unsigned int MaximumChannel;
};

/* 177 */
struct $66D8BAE383F9288207BB026A64AFF51A
{
  unsigned int RequestLine;
  unsigned int Reserved;
  unsigned int Channel;
  unsigned int TransferWidth;
};

/* 81 */
struct $B14DB811EDFC1214B110A98B000FF49B
{
  unsigned int Data[3];
};

/* 178 */
struct $CF7D779FCF8501AF42168A39ACA3AE76
{
  unsigned int Length;
  unsigned int MinBusNumber;
  unsigned int MaxBusNumber;
  unsigned int Reserved;
};

/* 179 */
struct $5D61DD2957AFDEE7ED67BD2EDF2BEA99
{
  unsigned int Priority;
  unsigned int Reserved1;
  unsigned int Reserved2;
};

/* 180 */
struct $E1E24E5A6C2341D083EFEF793DAAE962
{
  unsigned int Length40;
  unsigned int Alignment40;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 181 */
struct $BA60B0CFBA5731E32F3E58AB6E50D7FF
{
  unsigned int Length48;
  unsigned int Alignment48;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 182 */
struct $778D959CC5D7C765A4014C50B76865DD
{
  unsigned int Length64;
  unsigned int Alignment64;
  _LARGE_INTEGER MinimumAddress;
  _LARGE_INTEGER MaximumAddress;
};

/* 87 */
struct $EDAC022CDA01C704ED739E663C6F28A2
{
  unsigned __int8 Class;
  unsigned __int8 Type;
  unsigned __int8 Reserved1;
  unsigned __int8 Reserved2;
  unsigned int IdLowPart;
  unsigned int IdHighPart;
};

/* 183 */
union $75BFDA8CAC480A7ACC111527D5475F8D
{
  $A46720D08D4953A701BC2CEF123A3A5E Port;
  $A46720D08D4953A701BC2CEF123A3A5E Memory;
  $C47234A5E135268FB8DC1B2B94727F34 Interrupt;
  $290D34FD7868E94AFEC0383C08CB9B28 Dma;
  $66D8BAE383F9288207BB026A64AFF51A DmaV3;
  $A46720D08D4953A701BC2CEF123A3A5E Generic;
  $B14DB811EDFC1214B110A98B000FF49B DevicePrivate;
  $CF7D779FCF8501AF42168A39ACA3AE76 BusNumber;
  $5D61DD2957AFDEE7ED67BD2EDF2BEA99 ConfigData;
  $E1E24E5A6C2341D083EFEF793DAAE962 Memory40;
  $BA60B0CFBA5731E32F3E58AB6E50D7FF Memory48;
  $778D959CC5D7C765A4014C50B76865DD Memory64;
  $EDAC022CDA01C704ED739E663C6F28A2 Connection;
};

/* 184 */
struct _IO_RESOURCE_DESCRIPTOR
{
  unsigned __int8 Option;
  unsigned __int8 Type;
  unsigned __int8 ShareDisposition;
  unsigned __int8 Spare1;
  unsigned __int16 Flags;
  unsigned __int16 Spare2;
  $75BFDA8CAC480A7ACC111527D5475F8D u;
};

/* 185 */
struct _IO_RESOURCE_LIST
{
  unsigned __int16 Version;
  unsigned __int16 Revision;
  unsigned int Count;
  _IO_RESOURCE_DESCRIPTOR Descriptors[1];
};

/* 186 */
struct _IO_RESOURCE_REQUIREMENTS_LIST
{
  unsigned int ListSize;
  _INTERFACE_TYPE InterfaceType;
  unsigned int BusNumber;
  unsigned int SlotNumber;
  unsigned int Reserved[3];
  unsigned int AlternativeLists;
  _IO_RESOURCE_LIST List[1];
};

/* 194 */
struct _POWER_SEQUENCE
{
  unsigned int SequenceD1;
  unsigned int SequenceD2;
  unsigned int SequenceD3;
};

/* 74 */
struct __unaligned __declspec(align(4)) $09B4B0FC5939EA7DD22DEFCB746563BE
{
  _LARGE_INTEGER Start;
  unsigned int Length;
};

/* 75 */
struct $B56176FCA237C2B0A687F85299143576
{
  unsigned int Level;
  unsigned int Vector;
  unsigned int Affinity;
};

/* 76 */
struct $7AC00411D044B43A85AFD80B1CBC99F4
{
  unsigned __int16 Reserved;
  unsigned __int16 MessageCount;
  unsigned int Vector;
  unsigned int Affinity;
};

/* 77 */
union $F4D0B3D7A5970000AE0DBF5E7C321576
{
  $7AC00411D044B43A85AFD80B1CBC99F4 Raw;
  $B56176FCA237C2B0A687F85299143576 Translated;
};

/* 78 */
struct $63BC109A07B2DDA49A730DDC4F45BDC8
{
  $F4D0B3D7A5970000AE0DBF5E7C321576 ___u0;
};

/* 79 */
struct $72748C417E05990EBECC6BB8D043D8B0
{
  unsigned int Channel;
  unsigned int Port;
  unsigned int Reserved1;
};

/* 80 */
struct $CC0360DD0852F9AAB36A2B2BBC2DF141
{
  unsigned int Channel;
  unsigned int RequestLine;
  unsigned __int8 TransferWidth;
  unsigned __int8 Reserved1;
  unsigned __int8 Reserved2;
  unsigned __int8 Reserved3;
};

/* 82 */
struct $6C467299E1DD150E8FDAFB428553E9E9
{
  unsigned int Start;
  unsigned int Length;
  unsigned int Reserved;
};

/* 83 */
struct $D735038633D506DCA1748B01FF7747C2
{
  unsigned int DataSize;
  unsigned int Reserved1;
  unsigned int Reserved2;
};

/* 84 */
struct __unaligned __declspec(align(4)) $D518B891DD5396E430DB20D2323601FA
{
  _LARGE_INTEGER Start;
  unsigned int Length40;
};

/* 85 */
struct __unaligned __declspec(align(4)) $5F798E27C3C40C4EF0E3132EDEF498B3
{
  _LARGE_INTEGER Start;
  unsigned int Length48;
};

/* 86 */
struct __unaligned __declspec(align(4)) $ABAF0F2993B64C070F6C726118993B07
{
  _LARGE_INTEGER Start;
  unsigned int Length64;
};

/* 88 */
union $2E4DD83A3D247D49C11FEB88956A4860
{
  $09B4B0FC5939EA7DD22DEFCB746563BE Generic;
  $09B4B0FC5939EA7DD22DEFCB746563BE Port;
  $B56176FCA237C2B0A687F85299143576 Interrupt;
  $63BC109A07B2DDA49A730DDC4F45BDC8 MessageInterrupt;
  $09B4B0FC5939EA7DD22DEFCB746563BE Memory;
  $72748C417E05990EBECC6BB8D043D8B0 Dma;
  $CC0360DD0852F9AAB36A2B2BBC2DF141 DmaV3;
  $B14DB811EDFC1214B110A98B000FF49B DevicePrivate;
  $6C467299E1DD150E8FDAFB428553E9E9 BusNumber;
  $D735038633D506DCA1748B01FF7747C2 DeviceSpecificData;
  $D518B891DD5396E430DB20D2323601FA Memory40;
  $5F798E27C3C40C4EF0E3132EDEF498B3 Memory48;
  $ABAF0F2993B64C070F6C726118993B07 Memory64;
  $EDAC022CDA01C704ED739E663C6F28A2 Connection;
};

/* 89 */
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR
{
  unsigned __int8 Type;
  unsigned __int8 ShareDisposition;
  unsigned __int16 Flags;
  $2E4DD83A3D247D49C11FEB88956A4860 u;
};

/* 202 */
struct _CM_PARTIAL_RESOURCE_LIST
{
  unsigned __int16 Version;
  unsigned __int16 Revision;
  unsigned int Count;
  _CM_PARTIAL_RESOURCE_DESCRIPTOR PartialDescriptors[1];
};

/* 203 */
struct _CM_FULL_RESOURCE_DESCRIPTOR
{
  _INTERFACE_TYPE InterfaceType;
  unsigned int BusNumber;
  _CM_PARTIAL_RESOURCE_LIST PartialResourceList;
};

/* 204 */
struct _CM_RESOURCE_LIST
{
  unsigned int Count;
  _CM_FULL_RESOURCE_DESCRIPTOR List[1];
};

/* 225 */
struct _SECTION_OBJECT_POINTERS
{
  void *DataSectionObject;
  void *SharedCacheMap;
  void *ImageSectionObject;
};

/* 226 */
struct _IO_COMPLETION_CONTEXT
{
  void *Port;
  void *Key;
};

/* 25 */
enum _SECURITY_IMPERSONATION_LEVEL : __int32
{
  SecurityAnonymous = 0x0,
  SecurityIdentification = 0x1,
  SecurityImpersonation = 0x2,
  SecurityDelegation = 0x3,
};

/* 130 */
struct __declspec(align(4)) _SECURITY_QUALITY_OF_SERVICE
{
  unsigned int Length;
  _SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  unsigned __int8 ContextTrackingMode;
  unsigned __int8 EffectiveOnly;
};

/* 131 */
struct _LUID
{
  unsigned int LowPart;
  int HighPart;
};

/* 132 */
struct _SECURITY_SUBJECT_CONTEXT
{
  void *ClientToken;
  _SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  void *PrimaryToken;
  void *ProcessAuditId;
};

/* 133 */
struct _LUID_AND_ATTRIBUTES
{
  _LUID Luid;
  unsigned int Attributes;
};

/* 134 */
struct _INITIAL_PRIVILEGE_SET
{
  unsigned int PrivilegeCount;
  unsigned int Control;
  _LUID_AND_ATTRIBUTES Privilege[3];
};

/* 135 */
struct _PRIVILEGE_SET
{
  unsigned int PrivilegeCount;
  unsigned int Control;
  _LUID_AND_ATTRIBUTES Privilege[1];
};

/* 136 */
union $ED099C261B46BE348525EDDB38989C95
{
  _INITIAL_PRIVILEGE_SET InitialPrivilegeSet;
  _PRIVILEGE_SET PrivilegeSet;
};

/* 137 */
struct _ACCESS_STATE
{
  _LUID OperationID;
  unsigned __int8 SecurityEvaluated;
  unsigned __int8 GenerateAudit;
  unsigned __int8 GenerateOnClose;
  unsigned __int8 PrivilegesAllocated;
  unsigned int Flags;
  unsigned int RemainingDesiredAccess;
  unsigned int PreviouslyGrantedAccess;
  unsigned int OriginalDesiredAccess;
  _SECURITY_SUBJECT_CONTEXT SubjectSecurityContext;
  void *SecurityDescriptor;
  void *AuxData;
  $ED099C261B46BE348525EDDB38989C95 Privileges;
  unsigned __int8 AuditPrivileges;
  _UNICODE_STRING ObjectName;
  _UNICODE_STRING ObjectTypeName;
};

/* 407 */
typedef _VSTOR_CHANNEL_ETW_TRACE_INFO *PVSTOR_CHANNEL_ETW_TRACE_INFO;

/* 436 */
typedef int __stdcall CHANNEL_EVENT_CALLBACK(VMBCHANNEL__ *, _VSTOR_PACKET *);

/* 537 */
typedef void (__stdcall *PVSTOR_CHANNEL_COMPLETION_ROUTINE)(VMBCHANNEL__ *, VSTOR_PACKET_OPERATION, _VSTOR_PACKET *, _VSTOR_CHANNEL_REQUEST *);

/* 594 */
typedef int (__stdcall *PCHANNEL_EVENT_CALLBACK)(VMBCHANNEL__ *, _VSTOR_PACKET *);

/* 767 */
typedef void __stdcall VSTOR_CHANNEL_COMPLETION_ROUTINE(VMBCHANNEL__ *, VSTOR_PACKET_OPERATION, _VSTOR_PACKET *, _VSTOR_CHANNEL_REQUEST *);

/* 805 */
typedef _VSTOR_CHANNEL_REQUEST *PVSTOR_CHANNEL_REQUEST;

